### ISSUE TITLE
Issue starting server

### ISSUE THREAD

**Issue by russjk** [rustdesk/rustdesk-server#10]
I am having trouble starting my own hosted server, it seems like there is an issue with the response from the license server.

![image](https://user-images.githubusercontent.com/19530620/131264088-a655754c-d573-46a7-9379-3c06608b79f2.png)

Would you be able to help?

Cheers

**Comment by rustdesk** [comment]
It is ok now. I am sorry, I upgraded my server yesterday.

**Comment by rustdesk** [comment]
It is free and open source now. https://rustdesk.com/docs/en/self-host/
