### ISSUE TITLE
hbbs cpu usage is high while setting up connection, Windows version

### ISSUE THREAD

**Issue by AiyiCN** [rustdesk/rustdesk-server#100]
1.1.6自建服务windows64x版本，部署和重启的时候都很正常，但有时候完成一次远程连接并结束连接后，hbbs这个服务cpu会飙满导致其他服务卡死，之后重启后才会正常。
<img width="1021" alt="截屏2022-08-19 下午3 53 26" src="https://user-images.githubusercontent.com/26990101/185574085-cd08dcc4-a1de-4ec0-be34-7d9df9e3c7b0.png">

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/issues/63

**Comment by rustdesk** [comment]
Close to favor https://github.com/rustdesk/rustdesk-server/issues/186

**Comment by rustdesk** [comment]
Can you try out this?

![image](https://user-images.githubusercontent.com/71636191/220841534-9bd479d8-1bf5-4dca-8e6e-cc0c69a308ce.png)
