### ISSUE TITLE
I got an error when I followed the tutorial to create a key pair

### ISSUE THREAD

**Issue by zlyzlyzlyzly** [rustdesk/rustdesk-server#101]
我使用以下命令
docker run --rm --entrypoint /usr/bin/rustdesk-utils  rustdesk/rustdesk-server-s6:latest genkeypair
创建密钥对时，出现如下错误
docker: Error response from daemon: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/bin/rustdesk-utils": stat /usr/bin/rustdesk-utils: no such file or directory: unknown.
有遇到过的吗？

**Comment by paspo** [comment]
because the docker images are not yet updated with these modifications; they'll be updated with next release.

**Comment by rustdesk** [comment]
Sorry for late, just created a pre-release for update docker, will be ready soon.

**Comment by paspo** [comment]
now docker images are published now, do this:

```bash
docker pull rustdesk/rustdesk-server-s6:latest 
```

and retry

```bash
# docker run --rm --entrypoint /usr/bin/rustdesk-utils rustdesk/rustdesk-server-s6:latest genkeypair
Public Key:  miGhZMXHeIBgkT1sAYnkYHFlVd+m6uZOaXGUACIXrSQ=
Secret Key:  usdm1TNKe3ED7FzOVcOEHcQcV1KjMXUnQh6tgpDlpWGaIaFkxcd4gGCRPWwBieRgcWVV36bq5k5pcZQAIhetJA==
```

**Comment by zlyzlyzlyzly** [comment]
Thank you. It's all right now

**Comment by paspo** [comment]
you can close this issue
