### ISSUE TITLE
hbbs error: Unable to open database file

### ISSUE THREAD

**Issue by miguelagve** [rustdesk/rustdesk-server#106]
**Describe the bug**
Every time I run hbbs the container exits inmediately with the following error on the logs>
`INFO [src/peer.rs:82] DB_URL=./db_v2.sqlite3
Error: An error occured while creating a new object: error returned from database: unable to open database file`
It happens whether I manually run hbbs and hbbr or using the provided docker-compose file with only the ip changed

**Describe the environment**
 - Install environment:  podman on Fedora 36, using latest container image

**Comment by paspo** [comment]
can you check the permissions on the db file and the containing directory?

**Comment by miguelagve** [comment]
I've tried both with the files owned by the user as well as root and get the same issue

**Comment by paspo** [comment]
if no database exists, it gets created by hbbs. 
Can you try without mounting the directory of the database?

**Comment by miguelagve** [comment]
I removed   `volumes:  - ./data:/root` from the docker-compose file and the container stays up just fine. I've managed to connect to my remote computer using the relay server. Thank you!

**Comment by paspo** [comment]
no, wait! That was only for testing!

If you leave like that, you have no persistence for your db and keys!

Right now, we know that it's not a problem in the container itself, and we can exclude the host also. The problem should be the mount. Can be a podman issue, IDK. 
Can you try to specify the full path in the docker-compose file?

instead of:

```yaml
  volumes:
    - ./data:/root
```

you try:


```yaml
  volumes:
    - /a/full/path/to/data:/root
```

**Comment by miguelagve** [comment]
Okay, I jumped to conclusions too fast :)
I'll give it a try, but I'm not sure it would make a difference, since the problem also showed up when running directly with docker using the following: 
`docker run --name hbbs --net=host -v "$PWD/data:/root" -d rustdesk/rustdesk-server:latest hbbs -r 127.0.0.1`

**Comment by paspo** [comment]
why you use `127.0.0.1` as relay? you should use something all your clients can reach

**Comment by miguelagve** [comment]
I was using the ip address of the server before and I was getting this error, so I changed to the loopback ip of my server to see if it had anything to do with that. I'm running the server locally and connecting with devices on the local network, so both should work just fine

**Comment by paspo** [comment]
definitely a podman "thing", in which I'm no expert. It involves SElinux.

I found a solution:

```bash
docker run --name hbbs --net=host -v "$PWD/data:/root:z" -d rustdesk/rustdesk-server:latest hbbs -r 127.0.0.1
```

**Comment by miguelagve** [comment]
I have been able to get the container up and running, even in a rootless container. The database and the keypair are created in the chosen directory and I'm able to create an encrypted remote connection. 
Thank you for your pacience.

**Comment by miguelagve** [comment]
I've made a small change to the readme file to note this issue with SELinux #108
