### ISSUE TITLE
Support for wayland

### ISSUE THREAD

**Issue by bhuvankrishna** [rustdesk/rustdesk-server#11]
I tested it with rustdesk version 1.1.8 on debian unstable with kernel version 5.10.0-8. I check the system service file and found that there are not logs being recorded. Maybe that is another feature that can be included. Meanwhile if there are any suggestions on how to support wayland I may give a try to work on it. 
![Screenshot from 2021-09-17 18-34-38](https://user-images.githubusercontent.com/592449/133787297-257b67e7-f507-4936-9f0e-e946d801cb5b.png)

Thanks again for such an awesome software. It simple works, I tested it on kde plasma with X11 and even the mobile app is great. It is consuming very little network bandwidth and there are so many features already.

**Comment by bhuvankrishna** [comment]
I think this issue needs to be reported in rust client.

**Comment by rustdesk** [comment]
Please check https://github.com/rustdesk/rustdesk/issues/56

**Comment by bhuvankrishna** [comment]
Thanks @rustdesk I am checking the same issue :)
