### ISSUE TITLE
Format error in synology DSM7.0

### ISSUE THREAD

**Issue by DanaHan** [rustdesk/rustdesk-server#12]
Recently, I try to install rustdesk-server spk package in synology DSM 7.0 system. But I get a package format error.
Can new spk build supported?

**Comment by rustdesk** [comment]
Yes, but I have no DSM 7.0 to test.

**Comment by rustdesk** [comment]
Yes, but I have no DSM 7.0 to test.

**Comment by rustdesk** [comment]
It is free and open source now. https://rustdesk.com/docs/en/self-host/
