### ISSUE TITLE
Got 0.0.0.0 and crash

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk-server#120]
**Describe the bug**
Got this when dev, but hard to reproduce.

**Describe the environment**
Linux

**How to Reproduce the bug**
hard to reproduce.

**Expected behavior**
0.0.0.0 should not happen, it is indeed a bug

**Comment by dmgolembiowski** [comment]
@rustdesk I've made a couple of comparisons relating the state of the repository on Linux compared to its current state on the master branch. 
After reviewing `git diff 1.1.6-1 master` there are a couple of substantial changes to the Linux-targeting source that substantiate this to be a stale issue:
-  `diff --git a/libs/hbb_common/src/platform/linux.rs b/libs/hbb_common/src/platform/linux.rs`
-  `diff --git a/libs/hbb_common/src/socket_client.rs b/libs/hbb_common/src/socket_client.rs`

Recommending that this be closed.
