### ISSUE TITLE
群晖Docker搭建完hbbs和hbbr，相关端口也已经开放，但是连接对方一直提示无法通过注册的服务器连接

### ISSUE THREAD

**Issue by wolfcdd** [rustdesk/rustdesk-server#127]
可以正常连接中继
![image](https://user-images.githubusercontent.com/5728354/195047747-362ca7ee-e9e9-4b4a-99e9-f0cc2434aba9.png)

点击连接提示：
![image](https://user-images.githubusercontent.com/5728354/195047541-af84505d-7abc-4a25-9c29-d8c2e05f6c1f.png)
![image](https://user-images.githubusercontent.com/5728354/195047860-c4c47a13-6e05-4eae-bd45-0d4417ae26c0.png)

相应配置都是自建的内容：
![image](https://user-images.githubusercontent.com/5728354/195048071-f1d46016-f313-4e57-87a4-27e23055bf58.png)

另一机器进行测试则一直提示被对方关闭：
![image](https://user-images.githubusercontent.com/5728354/195048229-dcd13fbc-f90b-4ade-8389-6899251f3d16.png)

群晖Docker相应配置：
hbbs：
![image](https://user-images.githubusercontent.com/5728354/195048572-636853d4-7b78-4aeb-b811-67614ab91c49.png)
![image](https://user-images.githubusercontent.com/5728354/195048676-8eb772ae-284f-4787-b70f-ce479cd451cb.png)
![image](https://user-images.githubusercontent.com/5728354/195048794-820db31e-4a58-4a04-8bcb-30988de537e5.png)

hbbr：
![image](https://user-images.githubusercontent.com/5728354/195048925-9dbe02df-36c3-4bde-a20d-493c4f625b3f.png)
![image](https://user-images.githubusercontent.com/5728354/195048978-e9b778d2-af16-421a-980d-858233d4cbd6.png)

请问还需要哪个地方进行修改吗，谢谢。

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/763

**Comment by cpsyun** [comment]
一样的问题，请问解决了吗？
