### ISSUE TITLE
password shown in plaintext in logs

### ISSUE THREAD

**Issue by ShadowVoyd** [rustdesk/rustdesk-server#128]
This is pretty simple, the password set for client to host in rustdesk is output to the log on the respective machines (in the config files too?) why is this happening?

**Comment by pirona** [comment]
I've got it all working on Debian 11 but this security flaw is pretty much a killer bug in my opinion, especially on Windows.

**Comment by rustdesk** [comment]
fixed in nightly build

**Comment by pirona** [comment]
Thanks !
