### ISSUE TITLE
Upgrade Rustdesk 1.16 to 1.16-1 using docker

### ISSUE THREAD

**Issue by vyncusp** [rustdesk/rustdesk-server#129]
Hi,
I have hosted rustdesk 1.16 install it using docker. 
How do I upgrade it to newest version 1.16-1?

Many thanks

**Comment by paspo** [comment]
`docker compose pull && docker compose up -d`

supposing you're using `docker compose`

**Comment by vyncusp** [comment]
Hi @paspo ,
I have tried 
luxius99@rustdesk:~$ docker compose pull && docker compose up -d
no configuration file provided: not found
luxius99@rustdesk:~$

Nothing happen

**Comment by paspo** [comment]
`no configuration file provided: not found` means you're not using **docker-compose**.

I think you should be more specific about your environment.

**Comment by vyncusp** [comment]
Hi,
Yes im sure i install rustdesk using docker
please see below image
![2022-10-26_17-49-52](https://user-images.githubusercontent.com/56208673/198007735-36278d51-81f6-4be8-881f-2098b723ab22.jpg)

**Comment by vyncusp** [comment]
Hi @paspo ,
Thanks you alot.

I successfully upgrade it. All i need to do is go to rustdesk docker folder
and run docker compose pull && docker compose up -d

Many thanks
