### ISSUE TITLE
Armhf docker images

### ISSUE THREAD

**Issue by MrAvana** [rustdesk/rustdesk-server#135]
It would be great if you can supply official armhf docker images  (armv7). Thank you in advance.

**Comment by paspo** [comment]
[Classic images](https://hub.docker.com/r/rustdesk/rustdesk-server) are supported for amd64 and arm64 only.
[S6 images](https://hub.docker.com/r/rustdesk/rustdesk-server-s6) supports amd64, arm64, i386 and armv7.

**Comment by MrAvana** [comment]
It worked perfectly. 🙏

**Comment by MrAvana** [comment]
Thanks
