### ISSUE TITLE
Server build for the MIPS arch

### ISSUE THREAD

**Issue by SemenMartynov** [rustdesk/rustdesk-server#136]
**Describe the solution you'd like**
Could you pls provide a server build for the MIPS(LE) architecture?
Given the low requirements of the server, this would allow it to run on a lot of cheap routers.

**Comment by paspo** [comment]
@rustdesk your opinion on this?

IMHO despite the low effort needed to generate a binary for this arch, I think the big issue will be that we have to officially support it...

**Comment by rustdesk** [comment]
Can we do it in your CI?

**Comment by paspo** [comment]
yes, it'll end up in [releases](https://github.com/rustdesk/rustdesk-server/releases/tag/1.1.6-1) as something like `rustdesk-server-linux-mips.zip`.
I think a specific docker image it's not needed, due to the fact that most probable target will be some "low-spec" router...

**Comment by paspo** [comment]
also, take into account [rust support](https://doc.rust-lang.org/nightly/rustc/platform-support.html) for this arch is not "tier 1"

**Comment by rustdesk** [comment]
> also, take into account [rust support](https://doc.rust-lang.org/nightly/rustc/platform-support.html) for this arch is not "tier 1"

Agree

**Comment by rustdesk** [comment]
We have no machine to test

**Comment by paspo** [comment]
I can propose: @SemenMartynov can clone the repo, alter the CI (https://github.com/rustdesk/rustdesk-server/blob/master/.github/workflows/build.yaml) and add the new arch at lines 34-37. 
If this gets enough traction, @rustdesk will think to support it.

**Comment by SemenMartynov** [comment]
Oh, thank you for such attention to my question and suggested option. I will try to follow the latter advice.

**Comment by paspo** [comment]
@SemenMartynov If you need some help on this, just ask. 

The fact that we don't support this arch officially, doesn't mean we don't care...
