### ISSUE TITLE
Did the self built server start charging? 

### ISSUE THREAD

**Issue by changelzj** [rustdesk/rustdesk-server#147]
Did the self built server start charging? Use the Docker command on the document to start the server. The container cannot be started, and the following log output is available

[2022-11-19T13:43:15Z ERROR hbbr::lic] Registered email required (-m option). Please pay and register on https://rustdesk.com/server.

thanks

**Comment by rustdesk** [comment]
update your docker image cache (China).

**Comment by changelzj** [comment]
> update your docker image cache (China).

thanks for you reply 

but sorry, I didn't understand. What is the operation of updating the image cache to China? Do I need to modify the image acceleration address? I currently use Alibaba Cloud's acceleration address

thanks
