### ISSUE TITLE
when?

### ISSUE THREAD

**Issue by RobertZh** [rustdesk/rustdesk-server#15]
"A totally new version will be ready to be downloaded soon."
when?

**Comment by verymilan** [comment]
that's a 404.

**Comment by rustdesk** [comment]
https://discord.com/invite/nDceKgxnkV   ->  faq-server-license channel

**Comment by aogg** [comment]
![image](https://user-images.githubusercontent.com/8998031/150646342-dfc8db50-1626-46bf-ad5f-9f4eabcbc108.png)
no open https://discord.com/i

**Comment by darkguy2008** [comment]
Such a bad idea to put FAQs and user info in Discord. Any way we can have an **official** answer in GitHub, where this project **is hosted** ? Thank you.

**Comment by hamaluik** [comment]
Here is all the discord says about this:

![750E5FEA-F3AA-49BD-863D-979482FA7568](https://user-images.githubusercontent.com/894782/151635361-4f778c37-1841-48a1-b2f8-738a966e3f28.jpeg)

**Comment by rustdesk** [comment]
It is free and open source now. https://rustdesk.com/docs/en/self-host/
