### ISSUE TITLE
systemd dependency on .deb package

### ISSUE THREAD

**Issue by robertomurta** [rustdesk/rustdesk-server#154]
How exactly is server dependent on systemd?
I use debian 11 with openrc replacing systemd, and for most packages without Gui or dbus requirements that's ok.
As it is sugested pm2 as process manager on install guide, I wonder if systemd really a dependency, without it on .deb, it would really ease things on scenarios like mine.

**Comment by robertomurta** [comment]
Ok, I'm already using .zip version instead of .deb one, much simpler to setup.
thank you.

**Comment by paspo** [comment]
As stated [here](https://github.com/rustdesk/rustdesk-server/issues/154#issuecomment-1327721805) and [here](https://wiki.debian.org/Init), the official debian 11 (bullseye) init system is systemd, even though other are supported. 
That covers the vast majority of the .deb install base.

If you really need support for other init system in deb packages, please consider sponsoring a developer ;)
