### ISSUE TITLE
Forbidden Symbols

### ISSUE THREAD

**Issue by kirudas** [rustdesk/rustdesk-server#155]
**Describe the bug**
I cannot type amount of special characters during remote connection. If I connected to somewhere I cannot type spanish characters o
accents using left or right Shift. It seems like the Shift keypress was disabled by the RustDesk.
**Describe the environment**
 - Simple connection to somewhere.

**How to Reproduce the bug**
1. Connect to somewhere.
2. Try to type Shift + (any key).

**Expected behavior**
Write special char, but It didn't detect the type so they write (any key) no the combination.

**Comment by paspo** [comment]
I think this is not related to rustdesk-server; opening a [ticket in the client repo](https://github.com/rustdesk/rustdesk/issues/new/choose) can be better.
