### ISSUE TITLE
Rust Desk Pro / Roadmap

### ISSUE THREAD

**Issue by HRA42** [rustdesk/rustdesk-server#158]
Hi Guys,

Great Software you have build.

I read a few comments mentioning a pro version of rust desk, I would love to pay for that if the address book is working and if I could have some kind of audit / user management system.

Do you have any Roadmap or ETA on that?

**Comment by WWoodpecker** [comment]
Same question from me, we are looking for an alternative to our current remote management tool (Too few functions) and Teamviewer (price too high), but without address book it is useless for us unfortunately.... 
Any ideas yet on what the licences should cost and how they will be allocated? Named, Concurrent (like Teamviewer)?
We would also like to be a beta tester to demonstrate it with an address book to our IT manager.

**Comment by rustdesk** [comment]
> ETA

1th June

**Comment by Apashh** [comment]
Amazing ! ;)

**Comment by bloesss** [comment]
> > ETA
> 
> 1th June for trial version. We are all engaged in open source RustDesk client side, very little time on the "Pro" version.

But what does that mean for future? Will the Adressbook feature cost on on premise servers? What costs do you plan?
Without knowing that, we can't begin to test rustdesk as an anydesk alternative.

**Comment by rustdesk** [comment]
Due to feedback from the internal testing, it isn’t ready to release even as alpha at the moment. Release needs to be delayed but won’t be more than 1 week.

Here is a snapshot:

![image](https://github.com/rustdesk/rustdesk-server/assets/71636191/e40a00d7-4642-402a-b90c-d135bfea363c)

Features: https://rustdesk.com/v2/pricing.html

**Comment by Apashh** [comment]
Nice its a good new ! 
I d'ont understand princing. You say on Free Plann that we can have unlimited devices but on Business Plan 500 managed devices.. What is the difference, we can only have 500 devices on own database ? its low ? What is a licence user ?
For example we are +5 technician and +50 customers and +1000 devices... 

![image](https://github.com/rustdesk/rustdesk-server/assets/83477029/0acd60bd-1937-4774-bd4f-ef5f871aa6c8)

**Comment by rustdesk** [comment]
All plans allow for an unlimited number of devices (unmanaged). The free plan does not have an account system, so all devices are considered unmanaged.

The licensed user is defined in the same way as in AnyDesk/TeamViewer.

Our managed device functionality is similar to that of TeamViewer, as described in this article: https://community.teamviewer.com/English/kb/articles/106782-managed-devices-general-information. It has fewer limitations compared to AnyDesk.

**Comment by Apashh** [comment]
Hmm ok ! 
So, manageed devices its a good plan for servers, nas... ? and unmanaged device for classic user (desktop/laptop) ?
For licence user, we can have only 1 licence/same account for ~5 technicians ?

**Comment by HRA42** [comment]
2 thoughts on pricing policy:

1. We need significantly more than 500 managed devices
2. A monthly payment option, especially for the personal plan, is necessary to ensure availability for private customers.

**Comment by dinger1986** [comment]
> 3 thoughts on pricing policy:
> 
> 1. We need significantly more than 500 managed devices
> 2. A monthly payment option, especially for the personal plan, is necessary to ensure availability for private customers.
> 3. Can we license our own servers to use the functionality in data centers provided by us?

For more than 500 devices please email sales@rustdesk.com, monthly payment is fine and you can self host.

**Comment by dinger1986** [comment]
> Hmm ok ! So, manageed devices its a good plan for servers, nas... ? and unmanaged device for classic user (desktop/laptop) ? For licence user, we can have only 1 licence/same account for ~5 technicians ?

For whats not listed please email sales@rustdesk.com

**Comment by mrdmiller2** [comment]
Will there be an option for annual payments (at a discount) as we try to do annual payments both to avoid monthly issues, but also to seek discounts/cost reduction where possible.

**Comment by dinger1986** [comment]
It is billed annually

**Comment by t3ramos** [comment]
any updates on the release?

**Comment by dinger1986** [comment]
Sorry, still doing some internal testing. Hopefully soon!

**Comment by Apashh** [comment]
Hey, would you like beta tester to check if an issue exist on different functions ? :)

**Comment by dinger1986** [comment]
> Hey, would you like beta tester to check if an issue exist on different functions ? :)

I’m sure you and half the community would 😀
