### ISSUE TITLE
Rustdesk connect to rdp session

### ISSUE THREAD

**Issue by fadlyfayruz** [rustdesk/rustdesk-server#162]
i have server with multiple RDP account. in anydesk i can connect remotely with any account with adding "/accountname" after anydesk id example : 123456789/windows1

how can i do it in rustdesk?

i know there is RDP connection in rustdesk. but using RDP connection make my thinclient disconnect from Remote Desktop Session.

Thanks..

**Comment by LucasChvg** [comment]
Hi, 
I have the same issue, did you manage to do it ?
Thanks

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/323
