### ISSUE TITLE
Add Windows version's runtime requirements/lib( Microsoft VC++ ) to RADME

### ISSUE THREAD

**Issue by DetectiveLemon** [rustdesk/rustdesk-server#163]
I'm using Windows Server 2019 to build self-host, and both hbbr.exe and hbbs.exe just didn't running.
I've tried manual's nssm&pm2. With nssm, the service won't start and getting error: "Unexpected status SERVICE_PAUSED in response to START control.". With pm2, status was "errored" or "stopped".
Both nssm and pm2 did not output any error log, so it took me a lot of time to find the problem.
It seems the windows version needs Microsoft Visual C++ to run, and server runs fine after I installed.
So any idea to write that at the README.md or maybe just mention this in the manual ?  I'm sure I'm not the only one get that problem.

**Comment by rustdesk** [comment]
Everyone can edit the README.md.
