### ISSUE TITLE
The dual network servers cannot communicate

### ISSUE THREAD

**Issue by ltpanmm** [rustdesk/rustdesk-server#164]
My server is dual network, intranet and internet. After the self built server, the address of the self built server is there. The intranet address is filled in for the intranet computer, and the internet address is filled in for the internet computer. Remote interworking is not possible. Will this be optimized in the future

**Comment by ltpanmm** [comment]
Can I do this through iptables forwarding? I tried for a long time, but I can't do it. If you have a meeting, give me some advice? The two network cards are wan: 10.10.10.10 lan: 1111.255.20

**Comment by andywang1011** [comment]
Hi，Have you solved your problem?

**Comment by ltpanmm** [comment]
> 你好，你的问题解决了吗？

No, I give up this for the time being

**Comment by rustdesk** [comment]
This is router specific problem, check out https://github.com/rustdesk/rustdesk/wiki/FAQ#deploy-rustdesk-server-in-intranet

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/issues/24#issuecomment-1234029480
