### ISSUE TITLE
test windows build unavailable

### ISSUE THREAD

**Issue by angelbbs** [rustdesk/rustdesk-server#165]
![2022-12-13_23-59-10](https://user-images.githubusercontent.com/11198603/207442328-ea31876e-75ec-49a8-997f-b65169f5e61a.png)

**Comment by paspo** [comment]
![image](https://user-images.githubusercontent.com/8970889/207449395-cbb0202e-fbbd-4fb8-bfd4-f9a8af6dc470.png)

https://github.com/rustdesk/rustdesk-server/releases/download/1.1.6-2/rustdesk-server-windows-x86_64.zip
