### ISSUE TITLE
Change ID reports 

### ISSUE THREAD

**Issue by memoody8** [rustdesk/rustdesk-server#167]
**Describe the bug**

**Describe the environment**
 - Install environment: docker, docker swarm, podman, kubernetes, or package
 - If available, the `docker-compose.yaml` file
 - If package, we need the distribution and release: Ubuntu 22.04, Debian 11, ...
 - Or if you're running the plain binary, how you're running it
 - In any case, you have to specify the version in use

**How to Reproduce the bug**
1. Given the previously described environment
2. Do this and that
3. I get this error

**Expected behavior**
This should happen instead.

**Additional context**

**Notes**
 - Please write in english only. If you provide some images in different languages, you're required to write a translation in english.
 - In any case, **NEVER** put here the content if your `id_ed25519` file

**Comment by paspo** [comment]
Please close this.
