### ISSUE TITLE
Change ID reports "Not yet supported by the server"

### ISSUE THREAD

**Issue by memoody8** [rustdesk/rustdesk-server#168]
When trying to change the ID in Ubuntu 18.04 or 20.04, it fails with a message of "Not yet supported by the server". I am running version 1.1.9 and server 1.1.6. 

I wish to deploy this on many systems, then change IDs to match my system hostnames. Without this, I can't use RS as my main solution. 

I think I saw another closed issue saying it was disabled without an explanation as to why or when it might be re-enabled. If this is the same issue, can you please provide an update?

**Comment by baltermia** [comment]
Still an issue as of 2025
