### ISSUE TITLE
User connected window keep apearing and desapearing constantly

### ISSUE THREAD

**Issue by jeffersoncgo** [rustdesk/rustdesk-server#170]
**Describe the bug**
The user connected window just keep apearing and desapearing constantly, and, as is apear as foreground, it just interrupt whathever you are doing, as it gain the focus over the keyboard.
Also, theres a way for it not apear when you are using just TCP Tunnel, not the remote acess.

**Describe the environment**
 - Install environment: docker Portainer
 - If package, we need the distribution and release: Windows 10

**Additional context**
In the machines that we use it, the internet speed is low(is in a remote and rural area), and way unstable.

**Comment by rustdesk** [comment]
Honestly, we have no way to help you on such env specific problem.
BTW, no way to use TCP tunnel only for now, also no plan yet.
