### ISSUE TITLE
How to RustDesk into a RustDesk Server

### ISSUE THREAD

**Issue by walter-astro** [rustdesk/rustdesk-server#175]
I have RustDesk server running on a raspberry pi and everything works. My question is how to remote login to the server using RustDesk on another computer? After I installed the server I installed rustdesk-1.1.9-raspberry-armhf.deb and set it to use the server IP and everything worked until I restarted the server pi. Now hbbs says port 21118 is already in use.

**Comment by rustdesk** [comment]
I notice such problem also, though seldomly users use rustdesk and rustdesk-server on the same machine.

**Comment by walter-astro** [comment]
I fixed it by removing the line "21118:21118" from the docker-compose.yml file for the hbbs ports: setting. Everything seems to work now.
