### ISSUE TITLE
Debian 11 packages not working

### ISSUE THREAD

**Issue by Polve** [rustdesk/rustdesk-server#179]
**Describe the bug**
I downloaded the two debs and installed them:
rustdesk-server-hbbr_1.1.7_amd64.deb  rustdesk-server-hbbs_1.1.7_amd64.deb

**Describe the environment**
 - debian 11 container undex LXC

**Expected behavior**
services should start regularly, instead I get these errors in the logs:

```
Jan 18 14:21:02 rustdesk systemd[4732]: rustdesk-hbbr.service: Failed to set up standard output: No such file or directory
Jan 18 14:21:02 rustdesk systemd[4732]: rustdesk-hbbr.service: Failed at step STDOUT spawning /usr/bin/hbbr: No such file or directory
Jan 18 14:21:02 rustdesk systemd[1]: Started Rustdesk Relay Server.
Jan 18 14:21:02 rustdesk systemd[1]: rustdesk-hbbr.service: Main process exited, code=exited, status=209/STDOUT
Jan 18 14:21:02 rustdesk systemd[1]: rustdesk-hbbr.service: Failed with result 'exit-code'.
Jan 18 14:21:12 rustdesk systemd[1]: rustdesk-hbbr.service: Scheduled restart job, restart counter is at 72.
Jan 18 14:21:12 rustdesk systemd[1]: Stopped Rustdesk Relay Server.
[...]
Jan 18 14:28:35 rustdesk systemd[4796]: rustdesk-hbbs.service: Failed to set up standard output: No such file or directory
Jan 18 14:28:35 rustdesk systemd[4796]: rustdesk-hbbs.service: Failed at step STDOUT spawning /usr/bin/hbbs: No such file or directory
Jan 18 14:28:35 rustdesk systemd[1]: Started Rustdesk Signal Server.
Jan 18 14:28:35 rustdesk systemd[1]: rustdesk-hbbs.service: Main process exited, code=exited, status=209/STDOUT
Jan 18 14:28:35 rustdesk systemd[1]: rustdesk-hbbs.service: Failed with result 'exit-code'.

```
The strange thing is that both /usr/bin/hbbr and /usr/bin/hbbs exist!

Any hints?

**Comment by fansuregrin** [comment]
I have the same problem. However, I checked that `/var/log/rustdesk/` exists. The service still quit.
```
7月 22 19:46:35 ubuntu-Super-Server systemd[1]: Started Rustdesk Signal Server.                                                                                                                                  7月 22 19:46:35 ubuntu-Super-Server systemd[573745]: rustdesk-hbbs.service: Failed to set up standard output: No such file or directory                                                                          7月 22 19:46:35 ubuntu-Super-Server systemd[573745]: rustdesk-hbbs.service: Failed at step STDOUT spawning /usr/bin/hbbs: No such file or directory                                                              7月 22 19:46:35 ubuntu-Super-Server systemd[1]: rustdesk-hbbs.service: Main process exited, code=exited, status=209/STDOUT                                                                                       7月 22 19:46:35 ubuntu-Super-Server systemd[1]: rustdesk-hbbs.service: Failed with result 'exit-code'. 
```
```
7月 22 19:46:13 ubuntu-Super-Server systemd[1]: Started Rustdesk Relay Server.                                                                                                                                   7月 22 19:46:13 ubuntu-Super-Server systemd[573380]: rustdesk-hbbr.service: Failed to set up standard output: No such file or directory                                                                          7月 22 19:46:13 ubuntu-Super-Server systemd[573380]: rustdesk-hbbr.service: Failed at step STDOUT spawning /usr/bin/hbbr: No such file or directory                                                              7月 22 19:46:13 ubuntu-Super-Server systemd[1]: rustdesk-hbbr.service: Main process exited, code=exited, status=209/STDOUT                                                                                       7月 22 19:46:13 ubuntu-Super-Server systemd[1]: rustdesk-hbbr.service: Failed with result 'exit-code'.
```

**Comment by dinger1986** [comment]
So the deb installer isn't creating the /var/log/rustdesk-server folder. I'll take a look at that, I think at the moment it's just creating /var/log/rustdesk

**Comment by dinger1986** [comment]
Are you using the debs provided here? Or from debians repos? If they are there I don't know

**Comment by TheRealPlasgianp** [comment]
I'm 

> I have the same problem. However, I checked that `/var/log/rustdesk/` exists. The service still quit.
> 
> ```
> 7月 22 19:46:35 ubuntu-Super-Server systemd[1]: Started Rustdesk Signal Server.                                                                                                                                
> 7月 22 19:46:35 ubuntu-Super-Server systemd[573745]: rustdesk-hbbs.service: Failed to set up standard output: No such file or directory                                                                          
> 7月 22 19:46:35 ubuntu-Super-Server systemd[573745]: rustdesk-hbbs.service: Failed at step STDOUT spawning /usr/bin/hbbs: No such file or directory                                                              
> 7月 22 19:46:35 ubuntu-Super-Server systemd[1]: rustdesk-hbbs.service: Main process exited, code=exited, status=209/STDOUT                                                                                       
> 7月 22 19:46:35 ubuntu-Super-Server systemd[1]: rustdesk-hbbs.service: Failed with result 'exit-code'. 
> ```
> 
> ```
> 7月 22 19:46:13 ubuntu-Super-Server systemd[1]: Started Rustdesk Relay Server.                                                                                                                                   
> 7月 22 19:46:13 ubuntu-Super-Server systemd[573380]: rustdesk-hbbr.service: Failed to set up standard output: No such file or directory                                                                          
> 7月 22 19:46:13 ubuntu-Super-Server systemd[573380]: rustdesk-hbbr.service: Failed at step STDOUT spawning /usr/bin/hbbr: No such file or directory                                                              
> 7月 22 19:46:13 ubuntu-Super-Server systemd[1]: rustdesk-hbbr.service: Main process exited, code=exited, status=209/STDOUT                                                                                       
> 7月 22 19:46:13 ubuntu-Super-Server systemd[1]: rustdesk-hbbr.service: Failed with result 'exit-code'.
> ```

Same problem
