### ISSUE TITLE
Socket Forbidden Error

### ISSUE THREAD

**Issue by abdullah-erturk** [rustdesk/rustdesk-server#193]
We use rustdesk server at our university.

For Windows Server with Rustdesk installed, I rebooted because of the update and Rustdesk is no longer running.

What would be the reason?

![rustdesk_server](https://user-images.githubusercontent.com/54866587/219041393-2318b722-2b59-412c-971a-24f29e5695fb.jpg)

**Comment by abdullah-erturk** [comment]
Solved.

I noticed that the background service of RustDesk.exe program causes this error when RustDesk client program is installed on an operating system with RustDesk Server installed at the same time.

When I uninstalled the RustDesk client program, everything went back to normal.

**Comment by rustdesk** [comment]
Thanks
