### ISSUE TITLE
Docker on Raspberry Pi

### ISSUE THREAD

**Issue by gnimor** [rustdesk/rustdesk-server#198]
I am trying to run the docker image on my rapsberry pi:
Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

I run docker with the following command:
docker run --name rustdesk-server --net=host -e "RELAY=XXX.XXX.XXX" -e "ENCRYPTED_ONLY=1" -v "$PWD/data:/data" -d rustdesk/rustdesk-server-s6:latest-armv7

When starting the docker container in my portainer instance I see the following output:

s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan crashed. Killing everything and exiting.
s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted

Any idea what's wrong here? Did I miss something?

**Comment by paspo** [comment]
I can't reproduce the issue on my PIs...
Can you provide some more info?

- hardware model
- operating system (and release)
- docker or podman? (and release)
- apparmor status

thanks

**Comment by gnimor** [comment]
OK, here some additional information:

Hardware Model:
Raspberry Pi 4 Model B Rev 1.1

OS:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Docker:
Docker version 20.10.22, build 3a2c30b

Apparmor:
Not available/installed

**Comment by gnimor** [comment]
In addition some more detailed log output:

Attaching to hbbs, hbbr
hbbs    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbs    | s6-svscan: warning: executing into .s6-svscan/crash
hbbs    | s6-svscan crashed. Killing everything and exiting.
hbbs    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbs    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbs    | s6-svscan: warning: executing into .s6-svscan/crash
hbbs    | s6-svscan crashed. Killing everything and exiting.
hbbs    | s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
hbbs    | s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
hbbs    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbs    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbs    | s6-svscan: warning: executing into .s6-svscan/crash
hbbs    | s6-svscan crashed. Killing everything and exiting.
hbbs    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbr    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbr    | s6-svscan: warning: executing into .s6-svscan/crash
hbbr    | s6-svscan crashed. Killing everything and exiting.
hbbr    | s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
hbbr    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbr    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbr    | s6-svscan: warning: executing into .s6-svscan/crash
hbbr    | s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
hbbr    | s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
hbbr    | s6-svscan crashed. Killing everything and exiting.
hbbr    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbr    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbr    | s6-svscan: warning: executing into .s6-svscan/crash
hbbr    | s6-svscan crashed. Killing everything and exiting.
hbbr    | s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
hbbr    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbr    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbr    | s6-svscan: warning: executing into .s6-svscan/crash
hbbr    | s6-svscan crashed. Killing everything and exiting.
hbbr    | s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
hbbr    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbr    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbr    | s6-svscan: warning: executing into .s6-svscan/crash
hbbr    | s6-svscan crashed. Killing everything and exiting.
hbbr    | s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
hbbr    | s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
hbbr    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbs    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbs    | s6-svscan: warning: executing into .s6-svscan/crash
hbbs    | s6-svscan crashed. Killing everything and exiting.
hbbs    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbr exited with code 111
hbbs exited with code 111
hbbs    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbs    | s6-svscan: warning: executing into .s6-svscan/crash
hbbs    | s6-svscan crashed. Killing everything and exiting.
hbbs    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbs    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbs    | s6-svscan: warning: executing into .s6-svscan/crash
hbbs    | s6-svscan crashed. Killing everything and exiting.
hbbs    | s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
hbbs    | s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
hbbs    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbs    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbs    | s6-svscan: warning: executing into .s6-svscan/crash
hbbs    | s6-svscan crashed. Killing everything and exiting.
hbbs    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbs    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbs    | s6-svscan: warning: executing into .s6-svscan/crash
hbbs    | s6-svscan crashed. Killing everything and exiting.
hbbs    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbs    | s6-svscan: warning: unable to iopause: Operation not permitted
hbbs    | s6-svscan: warning: executing into .s6-svscan/crash
hbbs    | s6-svscan crashed. Killing everything and exiting.
hbbs    | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
hbbs exited with code 111

**Comment by paspo** [comment]
> OS: PRETTY_NAME="Raspbian GNU/Linux 10 (buster)" 

- I downloaded (from [here](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-legacy)) the `Raspberry Pi OS Lite (Legacy)` version.
- I booted this image on a `Raspberry pi 4 Model B Rev 1.4` (this is what I have at hand)
- apt update && apt upgrade
- now I'm on `Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux`, exactly like yours
- (I didn't use the docker.io package from default repo because it's version 18.xx and we need 20)
- I installed docker using [the official script](https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script)
- `sudo docker run --name rustdesk-server --net=host -e "RELAY=127.0.0.1" -e "ENCRYPTED_ONLY=1" -d rustdesk/rustdesk-server-s6:latest-armv7`  I can reproduce the issue!

(BTW, you should use the generic `latest` tag, docker will select the appropriate image)

The cause is a library problem and the culprit is `libseccomp2`

Now for the solution.... you have to enable the backport repo and upgrade that library.

```
echo 'deb http://deb.debian.org/debian buster-backports main' | sudo tee -a /etc/apt/sources.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
sudo apt update
sudo apt install libseccomp2/buster-backports
```

then reboot and retry

**Comment by gnimor** [comment]
@paspo: Thanks for your update. Your suggestion works fine - now it is running :-)
