### ISSUE TITLE
self host without online license verification

### ISSUE THREAD

**Issue by kosyar** [rustdesk/rustdesk-server#20]
I need server in intronet?
perhaps you will do this. and yet I did not find prices. and where to pay for the server

**Comment by rustdesk** [comment]
Pricing is not ready. You can use demo account (-m demo) for trial until our pricing is out. 
You can give us an ask price to help us finalize the pricing.
Please follow up our update on twitter, https://twitter.com/rustdesk

**Comment by kosyar** [comment]
and there are chances that there will be a server without checking the online license. I would buy this. I have closed networks.

**Comment by kosyar** [comment]
maybe it's worth making a license through hasp or something like that

**Comment by rustdesk** [comment]
> hasp

`hasp`?

**Comment by kosyar** [comment]
https://cpl.thalesgroup.com/software-monetization/all-products/sentinel-hasp
https://sentineldongle.com/aladdin-hasp-4-hardlock-srm-hl/ 
usb key for license software.

**Comment by rustdesk** [comment]
Hardware solution is  not applicable for us.

**Comment by rustdesk** [comment]
> I just need it to work without internet. and keep the license

Yes, you will get it. 

BTW, why do not you use VNC or RDP in your intranet?

**Comment by kosyar** [comment]
I used to use teamviewer. and now the task. find solutions that will not close for any reason. so that it always works. that's what selfhost is for.

**Comment by rustdesk** [comment]
It is free and open source now.
