### ISSUE TITLE
rustdesk的自建服务器出现问题

### ISSUE THREAD

**Issue by cengzhijie3** [rustdesk/rustdesk-server#201]
我用的ipv6vps自建的docker容器并且配置了参数但是rustdesk每次都识别不了
<img width="1031" alt="截圖 2023-02-21 上午11 59 23" src="https://user-images.githubusercontent.com/89333400/220244223-3d4ac1f2-b222-4d0b-ac04-5f5e29ea8669.png">

**Comment by rustdesk** [comment]
nightly build please.

**Comment by ghwmx** [comment]
> 我用的ipv6vps但是自建的docker容器并且配置了参数rustdesk每次都识别不了 <img alt="截图 2023-02-21 上午11 59 23" width="1031" src="https://user-images.githubusercontent.com/89333400/220244223-3d4ac1f2-b222-4d0b-ac04-5f5e29ea8669.png">

您好，请问你解决了吗？我现在是用ivp6绑定的域名，通过nginx proxy manager反向代理内网的地址，端口21117，但是不行，请问有其他的解决方案吗？只有ipv6
