### ISSUE TITLE
my ipv6 url can not be parsed

### ISSUE THREAD

**Issue by cengzhijie3** [rustdesk/rustdesk-server#203]
我用的是ipv6的vps来搭建docker并解析了域名，但是rustdesk却无法识别
<img width="912" alt="截圖 2023-02-21 下午8 42 10" src="https://user-images.githubusercontent.com/89333400/220348014-34fcc0fc-932e-4ec5-a671-8d90b7fa9b8a.png">

**Comment by rustdesk** [comment]
You need to make sure `ping lokou.lokou.cf` work on your machine first?

**Comment by rustdesk** [comment]
#201
