### ISSUE TITLE
Debian bookworm support 

### ISSUE THREAD

**Issue by bmeirellesRJ** [rustdesk/rustdesk-server#211]
Hi friends, if it is possible to add support to install on debian bookworm

**Comment by paspo** [comment]
Debian bookworm is unreleased as of today. (see https://wiki.debian.org/DebianReleases)
We're targeting only supported OSes.
You can compile and report what happens...

**Comment by bmeirellesRJ** [comment]
Oi Paolo, thank you for your help.

I was able to install on Debian Bookworm, but only the X64 version

The install.sh script is not installing the version x86 even in the stable.

Thanks a lot for the help

**Comment by paspo** [comment]
what is the `install.sh` script? are you sure this is related to this repo?

**Comment by bmeirellesRJ** [comment]
Hi Paspo,

The script in the official documentation:

https://rustdesk.com/docs/en/self-host/install/

**Comment by paspo** [comment]
> https://rustdesk.com/docs/en/self-host/install/

The first line of that page says that the script is hosted on another repo and supported via discord.

**Comment by bmeirellesRJ** [comment]
Hi papso, thank you very much
