### ISSUE TITLE
It works fine on the same LAN, but I can't connect to different networks

### ISSUE THREAD

**Issue by breathiness** [rustdesk/rustdesk-server#213]
The Docker command from the homepage installed it very smoothly without any errors reported. It shows green ready status normally in both computer client and mobile client. When both devices are on the same LAN, they can be connected normally. However, after switching to a different network, I get a "Connection closed by other party" message.

![Snipaste_2023-03-06_23-06-08](https://user-images.githubusercontent.com/11361630/223149690-606d96c6-1fb3-4e6d-ad15-aa567d4aafb6.png)

![Snipaste_2023-03-06_22-43-12](https://user-images.githubusercontent.com/11361630/223149973-ecd210e7-7c33-40d2-a5bb-ade3616778d0.png)

![Snipaste_2023-03-06_23-05-29](https://user-images.githubusercontent.com/11361630/223150611-407cd598-5e3a-4784-b3cd-f1addfc7279a.png)

---
同一局域网内可以正常使用，但是不同网络无法连接
使用主页的Docker命令非常顺利地安装好了，没有出现报错。在电脑客户端和手机客户端都能正常显示绿色就绪状态。在两个设备都在同一局域网内时可以正常连接。但是切换到不同网络后会出现“连接被对方关闭”提示。

**Comment by DoM1niC** [comment]
yep same Problem I have some Subnets e.g. WLAN AP Subnet and the Connection to Relay and ID Server couldn't established

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#deploy-rustdesk-server-in-intranet
