### ISSUE TITLE
change id

### ISSUE THREAD

**Issue by WeiDongTang** [rustdesk/rustdesk-server#22]
Does the latest version of rustdek server docker turn off change ID？

**Comment by WeiDongTang** [comment]
1.1.4 there is changeid information in the log, but not in the latest version. Is there an opening method in 1.1.5？

**Comment by rustdesk** [comment]
Yes, it is turned off for the time being.

**Comment by WeiDongTang** [comment]
> Yes, it is turned off for the time being.

thanks，hope it can be used in the future

**Comment by hellger** [comment]
hope it can be used in the future,Thanks

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/509

**Comment by nashgoo** [comment]
> Yes, it is turned off for the time being.

why?

**Comment by Arrmm** [comment]
Having this feature turned off really defeats the purpose of this "was-once" wonderful tool!!  May I suggest that use the UUID is the primary key in SQLlite3 instead of ID, or add a new parameter called Nickname where it allows the client and the server to change the ID/name as often as you like.  It is SUCH AN IMPORTANT feature that I cannot stress enough

**Comment by jinweijie** [comment]
> Having this feature turned off really defeats the purpose of this "was-once" wonderful tool!! May I suggest that use the UUID is the primary key in SQLlite3 instead of ID, or add a new parameter called Nickname where it allows the client and the server to change the ID/name as often as you like. It is SUCH AN IMPORTANT feature that I cannot stress enough

it's possible to change the id with some tricks: https://github.com/rustdesk/rustdesk/issues/838

**Comment by Arrmm** [comment]
> > Having this feature turned off really defeats the purpose of this "was-once" wonderful tool!! May I suggest that use the UUID is the primary key in SQLlite3 instead of ID, or add a new parameter called Nickname where it allows the client and the server to change the ID/name as often as you like. It is SUCH AN IMPORTANT feature that I cannot stress enough
> 
> it's possible to change the id with some tricks: [rustdesk/rustdesk#838](https://github.com/rustdesk/rustdesk/issues/838)

Thank you for sharing!!  I am going to give it a try now.

**Comment by Yarrax** [comment]
have any issues fot now?

I use my own rustdesk-server and cannot change ID dor my rysdesktop client with my own server.

**Comment by Arrmm** [comment]
> have any issues fot now?
> 
> I use my own rustdesk-server and cannot change ID dor my rysdesktop client with my own server.

Everything works fine for me.

**Comment by joaoafricano** [comment]
My contribution for change RustDesk ID im PowerShell.

This script change de Rustdesk ID to a hostname off the machine.


------------------Code-------------------------------------------------------------------

net stop RustDesk
taskkill /im RustDesk /f
# Declare Variables
$nome = (Get-CimInstance -ClassName Win32_ComputerSystem).Name
$id = $id = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 1
$newId = "id = '$nome'"
# Read the file content using the Get-Content
$filecontent = Get-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml -Raw
#Print the file content
$filecontent
# Replace a line in a file
# $str.Replace("$id","$newId")
# Save the replace line in a file  
$filecontent.Replace("$id","$newId") | Set-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml                  
net start RustDesk

--------  End off Code --------------------------------------------

I hope this helps someone....

**Comment by LukaszFormela** [comment]
As an addendum to guide provider by @Arrmm, here's correct way to do it on Debian:

1. Close RustDesk window
2. `service rustdesk stop`
3. `nano ~/.config/rustdesk/RustDesk.toml`
4. Change value of `id` to "0", save the file
5. `rm -f /etc/machine-id /var/lib/dbus/machine-id`
6. `dbus-uuidgen --ensure=/etc/machine-id`
7. `dbus-uuidgen --ensure`
8, Run RustDesk - a new ID will be automatically generated.

Reference: [https://wiki.debian.org/MachineId](https://wiki.debian.org/MachineId)

**Comment by paspo** [comment]
> 5\. rm -f /etc/machine-id /var/lib/dbus/machine-id

Changing the machine id will impact a lot of things other than rustdesk!
As per the link you referenced, you will lose some "data", like:

- dhcp lease can change
- gnome screen layout 
- you can screw up systemd-efi bootloader

The procedure you suggested is used when dealing with cloned systems (e.g. you have a "master" image and clone it to 20 different computers, so you need different machine-ids)

**Comment by shahidullahr** [comment]
Open command prompt with administrator privilege and run this command 
" Net stop Rustdesk"
then find this file and edit your ID - 
C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml
and save.
after then run this command in command prompt
"Net start Rustdesk"

Thats all.

**Comment by ksingh7** [comment]
@shahidullahr   https://github.com/rustdesk/rustdesk/issues/838 , might be helpful to you

**Comment by ksingh7** [comment]
I am still wondering if anyone has figured out a neat way to get or set ID / Password to Rustdesk via CLI  , CLI argument is what we need , desperately need. 

Anyone ?

**Comment by trinvh** [comment]
MacOS instruction doesn't work for me. It's reset to the initial ID whenever the server started again

**Comment by Arrmm** [comment]
Looks like all the methods listed above are no longer working as from 1.2x release.  Can the dev or other experts share the new method?  I took a look at the `Rustdesk.toml` file and it looks like the `id` parameter is now replaced by `enc_id`, which is encrypted.

**Comment by Bosk22** [comment]
Here is something that worked for me on version 1.2.2, hopefully it will work for others.

1. Downgrade to a earlier version (I used v1.1.4)
2. Change the ID, Password and Salt in C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml to :-
id = '0'
password = ''
salt = ''
3. Reboot
4. Run Rusdesk - ID displayed as "0"
5. Then upgrade to V1.2.2
6. After the upgrade I was presented with a new 10 digit ID.

Hope that helps one

**Comment by montvid** [comment]
@joaoafricano thanks for the script! I modified it to change the password too @ksingh7 . Works with rustdesk server [1.1.9](https://github.com/rustdesk/rustdesk-server/releases/tag/1.1.9)

`﻿net stop RustDesk
taskkill /im RustDesk /f

$nome = (Get-CimInstance -ClassName Win32_ComputerSystem).Name
$id = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 1
$newId = "id = '$nome'"

$filecontent = Get-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml -Raw

$filecontent

$filecontent.Replace("$id","$newId") | Set-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml                  


$pass = "0091E/xd2j1SwSjna8Y1K9nAYpkBgutenZqliMnRCfhrk="
$pw = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 1 -Skip 1

$newPw = "password = '$pass'"

$filecontent = Get-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml -Raw

$filecontent

$filecontent.Replace("$pw","$newPw") | Set-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml
$pw = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 1 -Skip 1

net start RustDesk`

**Comment by adamency** [comment]
Today, there is an ad-hoc command for this `--set-id`. However it seems either it is enabled only for Rustdesk Pro and disabled on free self-hosted servers, or there is a bug in the framework, because it never works, even when following the [correct format of Rustdesk IDs](https://github.com/rustdesk/rustdesk/blob/c97cc15c0eaeffe98958cc405fb7020af674785d/libs/hbb_common/src/lib.rs#L238)

I always get this error:

```
> rustdesk --set-id a99999
server_not_support
```

It may be a misconfiguration on my end, but I don't see anything that would make this fail given everything else works perfectly. My context is a self-hosted `rustdesk-server` machine with a `rustdesk` instance on the same machine whose ID I'm trying to change.

@rustdesk Can you explain which one of these 3 cases it actually is:
- Pro-only feature
- bug
- should normally work for free self-hosted instances
?

Thanks in advance.

**Comment by nosmall** [comment]
> @rustdesk Can you explain which one of these 3 cases it actually is:
> 
> * Pro-only feature
> * bug
> * should normally work for free self-hosted instances
>   ?
> 
> Thanks in advance.

anyway, it looks like the server is self-hosted - so far this feature is not supported at all even by the gui client

![rd](https://github.com/rustdesk/rustdesk-server/assets/48532/0820e735-f216-4787-a2aa-a149ba27ebb0)

**Comment by montvid** [comment]
@adamency @nosmall on the site it says it is a paid feature. Thanks for the generous devs one can change the id via the script and it works on the free version. It's not a bug - it's a feature 🥳

**Comment by adamency** [comment]
@montvid I think you're misleaded, Rustdesk hasn't used the `id` field for a long time and only rely on `enc_id` now, which your script doesn't change, and cannot change if you don't know the encryption method. So changing the `id` field in the config does not change your actual Rustdesk ID at all. That's the whole problem. We have to change it via Rustdesk API.

Secondly, can you please provide the precise link where it says that `--set-id` is a paid feature ? Cause I've looked deeply in the docs and haven't find this. The only mention of the command I find in the docs doesn't say so: https://rustdesk.com/docs/en/client/#command-line-parameters

**Comment by Clifra-Jones** [comment]
Just a thought, If these features are not only available in the paid for version, then remove them from the interface of the community version. Leave them in the pro version branch. This will stop all the confusion!

Another thought is, how can we see the value of these features if we cannot test them? Right now, I'm not seeing it!

**Comment by msg7086** [comment]
@adamency I just replaced the enc_id line with `id = 'whatever-id'` in toml file and it seems to be working. I did it manually but the script seems to be written in a way that should also work. Have you actually tried?

**Comment by adamency** [comment]
@msg7086 I have set up multiple Rustdesk self-hosted servers, I've already done all this many times. You most likely has the enc_id already set up and cached by Rustdesk on a location you didn't realized. Are you on Windows ? Rustdesk on Windows creates mirrors of your config in AppData and this is the actual source-of-truth location for the binary.

**Comment by msg7086** [comment]
@adamency Yeah I'm not sure. But after I change the id and start the service, I'm able to connect using the new custom id instead of the old digits numbers.

**Comment by Sven1403** [comment]
Hello,

i am using the script method to change the RustDesk ID with the hostname and its working normally. But i got a problem now. A new employee got a Laptop. The hostname of the Laptop was already used in the company and RustDesk was installed there. So when i run the Change ID script, the hostname wont be accepted from RustDesk and it is changing the ID to a random one. Here a example:

Old employee had a laptop with hostname "ABC123" and the ID of RustDesk was "ABC123" then. Now the new employee has a laptop with the hostname "ABC123" (the old laptop has been wiped or he is using this old laptop) and RustDesk dont accept the hostname "ABC123". If i add a character to the hostname like "ABC123A", its working and ID get changed.

Why is this happening? Are the IDs saved on my self hosted server somewhere? Anyway to clean this or allow duplicates?

**Comment by Sven1403** [comment]
>Try cleaning the RustDesk server database. The name is already associated with a machine that no longer exists. When this happens to me I delete the container from the server and create it again. With this, the machines register themselves again.

Hey @joaoafricano thanks for your reply. So how exactly you delete the container? Can you explain it? :)

**Comment by joaoafricano** [comment]
> > Try cleaning the RustDesk server database. The name is already associated with a machine that no longer exists. When this happens to me I delete the container from the server and create it again. With this, the machines register themselves again.
> 
> Hey @joaoafricano thanks for your reply. So how exactly you delete the container? Can you explain it? :)

Do you use Self-host?
If so, do you use Docker installation?

**Comment by Sven1403** [comment]
@joaoafricano yeah self hosted with a docker

**Comment by joaoafricano** [comment]
> @joaoafricano yeah self hosted with a docker

On the server, type :

docker ps -a --format '{{.Names}}'

in my case de result is:

portainer
passbolt-passbolt-1
passbolt-db-1
droppy
hbbs
hbbr


then  type :

docker rm -f hbbs  => to kill and delete hbbs service

docker rm -f hbbr => to kill and delete hbbr service

then reinstall de docker again.

Be careful when using the docker rm command.
may delete the wrong container.

Use at your own risk

**Comment by Sven1403** [comment]
@joaoafricano thanks alot! I guess _"then reinstall de docker again"_ isnt only docker-compose or? :'D or its so simple? 😄

**Comment by joaoafricano** [comment]
> @joaoafricano thanks alot! I guess _"then reinstall de docker again"_ isnt only docker-compose or? :'D or its so simple? 😄

Use de same file .yml you used when install for dthe first time.
then use "docker-compose up -d"command.
Hope this helps.

**Comment by Sven1403** [comment]
@joaoafricano thanks alot! i will try it soon :)

**Comment by MarkoCuk27** [comment]
As some have already mentioned, the ID is encrypted in newer versions and can no longer be easily changed using notepad Rustdesk.toml. However, it is possible to use id as a key instead of enc_id in Rustdesk.toml and then enter your desired ID as a string. Of course, stop the service beforehand and then start it again.

**Comment by C-Duv** [comment]
Yes, modifying in `Rustdesk.toml` to set the desired ID in `id` key and delete the `enc_id` works.

Note that at the next application execution, the provided `id` will be encrypted and moved to the `enc_id` key.

**Comment by Sven1403** [comment]
> > @joaoafricano yeah self hosted with a docker
> 
> On the server, type :
> 
> docker ps -a --format '{{.Names}}'
> 
> in my case de result is:
> 
> portainer passbolt-passbolt-1 passbolt-db-1 droppy hbbs hbbr
> 
> then type :
> 
> docker rm -f hbbs => to kill and delete hbbs service
> 
> docker rm -f hbbr => to kill and delete hbbr service
> 
> then reinstall de docker again.
> 
> Be careful when using the docker rm command. may delete the wrong container.
> 
> Use at your own risk

Hello @joaoafricano i finally tried it. I had to delete the sqlite database file also. After that it worked :)

**Comment by surfining** [comment]
> @joaoafricanoспасибо за скрипт! Я его модифицировал, чтобы тоже сменить пароль@ksingh7. Работает с сервером rustdesk [1.1.9](https://github.com/rustdesk/rustdesk-server/releases/tag/1.1.9)
> 
> ```
> net stop RustDesk
> taskkill /im RustDesk /f
> 
> $nome = (Get-CimInstance -ClassName Win32_ComputerSystem).Name
> $id = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 1
> $newId = "id = '$nome'"
> 
> $filecontent = Get-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml -Raw
> 
> $filecontent
> 
> $filecontent.Replace("$id","$newId") | Set-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml                  
> 
> 
> $pass = "password"
> $pw = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 1 -Skip 1
> 
> $newPw = "password = '$pass'"
> 
> $filecontent = Get-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml -Raw
> 
> $filecontent
> 
> $filecontent.Replace("$pw","$newPw") | Set-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml
> $pw = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 1 -Skip 1
> 
> net start RustDesk
> ```

Большое спасибо!
Работает на версии 1.3.2

**Comment by GetRektAgain** [comment]
![image](https://github.com/user-attachments/assets/0d550fb8-3061-49f2-b7a0-f5e24a0da9d7)
It Works! Save the script as .ps1 in C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config
Set the nome(ID) and pass (Password) in the script and then just run it as admin. 

Worked pretty good. Just make a backup upfront cause you cant have enough backup. 


> > @joaoafricanoспасибо за скрипт! Я его модифицировал, чтобы тоже сменить пароль@ksingh7. Работает с сервером rustdesk [1.1.9](https://github.com/rustdesk/rustdesk-server/releases/tag/1.1.9)
> > ```
> > net stop RustDesk
> > taskkill /im RustDesk /f
> > 
> > $nome = (Get-CimInstance -ClassName Win32_ComputerSystem).Name
> > $id = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 1
> > $newId = "id = '$nome'"
> > 
> > $filecontent = Get-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml -Raw
> > 
> > $filecontent
> > 
> > $filecontent.Replace("$id","$newId") | Set-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml                  
> > 
> > 
> > $pass = "password"
> > $pw = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 1 -Skip 1
> > 
> > $newPw = "password = '$pass'"
> > 
> > $filecontent = Get-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml -Raw
> > 
> > $filecontent
> > 
> > $filecontent.Replace("$pw","$newPw") | Set-Content -Path C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml
> > $pw = Get-Content C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 1 -Skip 1
> > 
> > net start RustDesk
> > ```
> 
> Большое спасибо! Работает на версии 1.3.2
> 
> Чтобы установить произвольное Имя я изменил: $nome = "<You_Name>"

**Comment by evripidis** [comment]
> #> > Having this feature turned off really defeats the purpose of this "was-once" wonderful tool!! May I suggest that use the UUID is the primary key in SQLlite3 instead of ID, or add a new parameter called Nickname where it allows the client and the server to change the ID/name as often as you like. It is SUCH AN IMPORTANT feature that I cannot stress enough
> 
> > it's possible to change the id with some tricks: [rustdesk/rustdesk#838](https://github.com/rustdesk/rustdesk/issues/838)
> 
> Thank you for sharing!! I am going to give it a try now.
> 
> Edit: Perfect! This is exactly what I needed. Here are the exact steps I took:
> 
> For Windows:
> 
> * Open Command Prompt with administrator access.
> * run 'net stop rustdesk'
> * run 'cd  C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config'
> * run 'notepad Rustdesk.toml' and edit the ID (see notes 1).
> * save the changes and exit notepad.
> * run 'net start rustdesk'
> 
> For MacOS:
> 
> * Stop Ruskdesk services
> * Close Rustdesk app
> * Open Terminal
> * run `cd /Users/<usermame>/Library/Preferences/com.carriez.RustDesk`
> * run `nano Rustdesk.toml` and edit the ID (see notes 1).
> * save the changes and reboot, and start the Rushdesk service again (see notes 2).
> 
> For Linux:
> 
> * Stop Ruskdesk services
> * Close Rustdesk app
> * Open Terminal
> * run `cd /root/.config/rustdesk`
> * run `nano Rustdesk.toml` (or use your favorite editor like gedit, etc) and edit the ID (see notes 1).
> * save the changes and reboot, and start the Rushdesk service again (see notes 2).
> 
> Notes 1: you can only name your ID with 'A-Z', '0-9', and '_'. Also, it is my understanding that there is a requirement of a minimum of 6 and a maximum of 16 characters. This is based on the pre-1.1.5 version of the server and someone would need to verify that.

Is this still valid ? I am trying that on Linux but it does not seem to have any effect.

**Comment by Arrmm** [comment]
> Is this still valid ? I am trying that on Linux but it does not seem to have any effect.

Only if you install client version 1.1.9 first, perform the steps above, confirm the changes are made correctly, and then upgrade to the latest.  Unfortunately, the trick stopped working since 1.2.0.

**Comment by Arrmm** [comment]
Maybe I am wrong but last time I checked was v1.2.x  and the method that I shared above didn't work.  I ended up rolling back to 1.1.9, change the name and then upgrade.  Unless they changed it again in 1.3.x but I doubt it.

**Comment by lolminerxmrig01** [comment]
can help me for change id windows cmd ( No Powershell ).
thanks a lot.

**Comment by Arrmm** [comment]
> can help me for change id windows cmd ( No Powershell ). thanks a lot.

Follow my Windows instructions above by installing v1.1.9 first, and then upgrade to the latest once the right ID is set.

**Comment by ThomasWaldmann** [comment]
I wasted some hours trying all sorts of solutions from the above posts, but nothing worked for me. I just wanted to get rid of all rustdesk configuration information and start from scratch (including rustdesk generating a new ID).

I successfully used this script. I noticed that the generated ID somehow depends on the machine, so if you have a main machine and some clones of that (via a disk imaging software), only the clones will get a new and different ID, but the main machine will generate the same ID again.

rustdesk-delete-config.cmd:
```
@echo off
setlocal EnableDelayedExpansion

echo ===============================================
echo RustDesk Configuration Reset Script
echo ===============================================
echo.
echo This script will:
echo - Stop all RustDesk processes
echo - Delete all RustDesk configuration files
echo.
echo WARNING: This will remove all saved connections,
echo settings, and force generation of a new ID.
echo.
pause

echo Stopping RustDesk...

taskkill /f /im rustdesk.exe 2>nul
timeout /t 3 /nobreak >nul

echo Removing RustDesk configuration files...

REM Remove user configuration directory
if exist "%APPDATA%\RustDesk" (
    echo   - Removing %APPDATA%\RustDesk
    rmdir /s /q "%APPDATA%\RustDesk"
)

REM Remove service configuration directory
if exist "%WINDIR%\ServiceProfiles\LocalService\AppData\Roaming\RustDesk" (
    echo   - Removing %WINDIR%\ServiceProfiles\LocalService\AppData\Roaming\RustDesk
    rmdir /s /q "%WINDIR%\ServiceProfiles\LocalService\AppData\Roaming\RustDesk"
)
```

**Comment by dielatin-04** [comment]
@joaoafricano thanks!!!!

I don't know about scripts and such....
I had a problem with the Rust ID of one PC which was connected to our previous self-hosted server.
Most of us we don't have Rust permanently installed on our computers, so no service is running.
Just for support when needed.
Playing with his script, I managed to finally change the Rust ID with the following in PowerShell.
~~~~~~~~~~~~~~~~~~~~~
$nome = '444 555 777'
$id = Get-Content C:\Users\user1\AppData\Roaming\RustDesk\config\RustDesk.toml | Select -First 1
$newId = "id = '$nome'"

$filecontent = Get-Content -Path C:\Users\user1\AppData\Roaming\RustDesk\config\RustDesk.toml -Raw

$filecontent

$filecontent.Replace("$id","$newId") | Set-Content -Path C:\Users\user1\AppData\Roaming\RustDesk\config\RustDesk.toml
~~~~~~~~~~~~~~~~~~~~~
Be careful where user1=your user name on Win. (Look carefully at the path and change it accordingly.)
Now this PC have the new ID 444 555 777 and it works normally.
