### ISSUE TITLE
Please add ipv6 resolution to rustdesk, now rustdesk only recognises ipv4 addresses, not ipv6 address

### ISSUE THREAD

**Issue by cengzhijie3** [rustdesk/rustdesk-server#234]
Please add ipv6 resolution to rustdesk, now rustdesk only recognises ipv4 addresses, not ipv6 address
<img width="912" alt="截圖 2023-04-01 上午10 12 21" src="https://user-images.githubusercontent.com/89333400/229261129-bce95309-9fc9-4ccc-aa43-ceecd1dad76f.png">
<img width="912" alt="截圖 2023-04-01 上午10 12 06" src="https://user-images.githubusercontent.com/89333400/229261132-a5fef74c-3001-4f4a-86bf-d0c57740a9a8.png">
<img width="912" alt="截圖 2023-04-01 上午10 13 09" src="https://user-images.githubusercontent.com/89333400/229261140-1edd3148-d3e2-4eac-b049-5a7f8ab19c90.png">
<img width="912" alt="截圖 2023-04-01 上午10 15 49" src="https://user-images.githubusercontent.com/89333400/229261189-4c3fbf58-c58d-498e-84dc-0835ce3c4b84.png">
<img width="912" alt="截圖 2023-04-01 上午10 13 09" src="https://user-images.githubusercontent.com/89333400/229261204-2c9649d3-3228-45d4-acbd-3d00e670e4d3.png">

**Comment by rustdesk** [comment]
Do not repeat your issue with out any search.
