### ISSUE TITLE
Can't remote to multiple workstation using Rustdesk since this afternoon on 5 April 23

### ISSUE THREAD

**Issue by mogitsupport** [rustdesk/rustdesk-server#237]
Hi, 

We are encounter the issue for remote to multiple workstation via Rustdesk since this afternoon. 

Some of them showing the error : 
<img width="376" alt="ErrorConnect_RustDesk" src="https://user-images.githubusercontent.com/129943667/230035315-6114b881-c5ac-4acd-81c8-ac52e15af478.PNG">

Can I check whether Rustdesk server from your side having issue currently?

Kindly assist and advice, thanks.

**Comment by albgen** [comment]
same here...

**Comment by jojoj223** [comment]
same here......... really need this issue to be solved ASAP

**Comment by albgen** [comment]
i just setup my own server...

**Comment by jojoj223** [comment]
did it work ? when you setup you rown server

**Comment by leesamuelm** [comment]
Of course, I would love to setup my own server. There seems to be a few options out there, but I honestly don't have the cycles to learn how and decide which method to do so. Oh and also, I'm remotely located from the two machines I'm trying to access, and cannot update the relay without being there.

**Comment by albgen** [comment]
> did it work ? when you setup you rown server

of course it worked :)
I have already a server rented, dns..and docker...:)
