### ISSUE TITLE
Change ID does not work

### ISSUE THREAD

**Issue by albgen** [rustdesk/rustdesk-server#241]
**Describe the bug**
Change ID does not work

**Describe the environment**
Using default server. Windows Client 1.1.9

**How to Reproduce the bug**
Just try to change the ID

**Expected behavior**
Change the ID 

**Additional context**

**Notes**
![image](https://user-images.githubusercontent.com/7231968/231187933-e45ac5ab-1056-4ff3-8c7d-c6cefc6d1db2.png)

**Comment by feedmes1eep** [comment]
https://github.com/rustdesk/rustdesk-server/issues/22

**Comment by albgen** [comment]
Since the feature is on the menu of the client, does that mean it will be supported in the future?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#change-id-addressbookapilogin-and-web-console
