### ISSUE TITLE
Keyboard keys Up,Down,Left,Right does not work at all in the following scenario(putty running on remote)

### ISSUE THREAD

**Issue by albgen** [rustdesk/rustdesk-server#243]
**Describe the bug**
Keyboard Keys Up,Down,Left,Right does not work in the following scenario.
Se section below

**Describe the environment**
 - Install environment: docker compose
 -  `docker-compose.yaml` file [docker-compose.yml.txt](https://github.com/rustdesk/rustdesk-server/files/11209814/docker-compose.yml.txt)
 - Both clients running V1.1.9. Windos version

**How to Reproduce the bug**
1. Connect to the remote Windows Desktop
2. Run putty on the remote Windows Desktop
3. Connect with putty on a ssh server
4. Try the arrows keys and you should see the last commands, instead you see nothing

Please note that, while the putty exe has the focus, the arrow keys does not work at all.

**Expected behavior**
Arrow keyboard to work properly

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1681
