### ISSUE TITLE
1.1.7-4 windows - wrong firewall rules

### ISSUE THREAD

**Issue by zen010101** [rustdesk/rustdesk-server#250]
**Describe the bug**
the path in the rule is wrong.

should be:  %ProgramFiles%\RustDeskServer\bin\hbbr.exe
but: %ProgramFiles%\RustDeskServer\hbbr.exe

missing '\bin'

so, the rules not working at all .

**Comment by doslager** [comment]
also seems to be an issue in pre-release 1.1.8.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/commit/c8719784751af9393b2e8d0c3fb9e8dc52f450d2
