### ISSUE TITLE
server-linux asset missing on releases

### ISSUE THREAD

**Issue by webfrequent-de** [rustdesk/rustdesk-server#258]
Hi rustdesk team,

the required rustdesk-server-linux-ARCH.zip for the linked ./install and ./update scripts are missing on the relase page for 1.1.8

`Upgrading Rustdesk Server
--2023-06-08 10:37:00--  https://github.com/rustdesk/rustdesk-server/releases/download/1.1.8/rustdesk-server-linux-amd64.zip
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-06-08 10:37:00 ERROR 404: Not Found.`

**Comment by rustdesk** [comment]
no hurry, CI is not finished.

**Comment by webfrequent-de** [comment]
Confirmed. Sorry for my impatience 👍 
![image](https://github.com/rustdesk/rustdesk-server/assets/105105408/0647d837-8945-459c-b7b7-1542c92f8524)
