### ISSUE TITLE
rustdesk-server 1.1.8

### ISSUE THREAD

**Issue by PnYMaT** [rustdesk/rustdesk-server#259]
Hi, i see a rustdesk-server release 1.1.8 but all files are named 1.1.7. I miss something ?

![2023-06-08_12h54_36](https://github.com/rustdesk/rustdesk-server/assets/60741252/2e49e53b-3439-4312-9af9-cf3daef29c1a)

**Comment by ich777** [comment]
Noticed the same, maybe it's just the wrong name?
Will this be fixed?

**Comment by rustdesk** [comment]
fixed
