### ISSUE TITLE
id_ed25519 files included in release package

### ISSUE THREAD

**Issue by doslager** [rustdesk/rustdesk-server#264]
Working with Windows Rust Server version 1.18 pre-release. When you unzip the files, it includes the id_ed25519/id_ed25519.pub files. I believe the install creates a new cert file when the services start up. 

IMO, the files should not be included in the release package. Seems confusing and could lead to someone trying to use those files which the entire world knows their cert and pub key. 

Just my $0.02. Thank you!

**Comment by doslager** [comment]
Sorry...this shouldnt be labeled a bug. More like "invalid". Not sure how to edit labels once the original post is posted.

**Comment by rustdesk** [comment]
Where is id file?
![image](https://github.com/rustdesk/rustdesk-server/assets/71636191/7129c5c4-7f46-484d-b1e7-d50f4b9ae4d6)

**Comment by doslager** [comment]
Nevermind. You can ignore/delete this. Sorry for the confusion. In my unzipped folder they were there. They must've been generated during the install. I re-downloaded the 1.18 release and nothing is in there. Sorry for the confusion. Thank you!
