### ISSUE TITLE
Anti-Virus picked up server-windows as "Win32:MalwareGen" 

### ISSUE THREAD

**Issue by PrinceC749926** [rustdesk/rustdesk-server#268]
![image_2023-07-02_033646972](https://github.com/rustdesk/rustdesk-server/assets/100583791/77b101c3-d840-4be7-ab25-b6cd4b35b8ba)

I have attached the alert I get when trying to download the zip file from github.

I am running Windows 10 Pro with the latest updates.
Using AVG Internet Security.

Can someone please let me know if this is a false positive or has there been a contamination of the Windows-Server file?

This is the place for generic questions. Please stay on topic and be polite.

**Notes**
 - Please write in english only. If you provide some images in different languages, you're required to write a translation in english.
 - In any case, **NEVER** put here the content if your `id_ed25519` file

**Comment by DevJupyHUB** [comment]
Hi there,

@PrinceC749926 " let me know if this is a false positive"

Recently Avast (who is related to AVG and/or vica - versa) also sends the desktop version (nightly) for testing. Good news, they sent the result today that it is clean (it is an automated process)

![2023-07-02_12h09_15](https://github.com/rustdesk/rustdesk-server/assets/125738232/e1e4fa92-0a15-4f90-a977-e01c99d67ddf)


the verdict is that the "alarm" was probably **false positive**

BTW:
I have not experienced this with the server version...

Br,
SedonD
