### ISSUE TITLE
Infection detected by AVG antivirus

### ISSUE THREAD

**Issue by croscwa** [rustdesk/rustdesk-server#273]
**Describe the bug**
Got the following AVG report when downloading [rustdesk-server-windows-x86_64.zip](https://github.com/rustdesk/rustdesk-server/releases/download/1.1.8/rustdesk-server-windows-x86_64.zip):

We've safely aborted connection on objects.githubusercontent.com because it was infected with Win32:Malware-gen

**Describe the environment**
 This message came up after going to the GitHub site and double-clicking on the x86 link, under Windows 11.

**Comment by paspo** [comment]
I [checked](https://www.virustotal.com/gui/url/36700d00c62d35ab1916b0cbfac5fede22af243030ae0a8b0793d3ebdad14d2b) that exact link with [VirusTotal](https://www.virustotal.com) and nothing is reported.

Please let's avoid a thread on AVG's reputation.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/issues/268
