### ISSUE TITLE
After 1.2.0 update, id at RustDesk.toml is encrypted and not possible to change

### ISSUE THREAD

**Issue by AlexanderKgr** [rustdesk/rustdesk-server#275]
After update and test the 1.2.0 client it wasn't possible for me to change the id of the client.
I suppose that the id is encrypted because it is written "enc_id"
Any info about this?

**Comment by Arrmm** [comment]
My only work around is to install the old one (pre 1.2), and then update to 1.2x, or until someone shares how to generate the `enc_id` from a standard ID name.
