### ISSUE TITLE
Windows server program

### ISSUE THREAD

**Issue by JustinWebDev** [rustdesk/rustdesk-server#278]
This is the place for generic questions. Please stay on topic and be polite.

The instructions here https://rustdesk.com/docs/en/self-host/windows/#run-hbbr-and-hbbs says to download the Windows server program, but the noted releases page doesn't show any Windows program.  Where can it be found?

**Comment by dinger1986** [comment]
https://github.com/rustdesk/rustdesk-server/releases/download/1.1.8/rustdesk-server-windows-x86_64.zip

**Comment by JustinWebDev** [comment]
Sorry - I didn't see the 'show all' link.  Thanks.
