### ISSUE TITLE
The function of copying and pasting files has failed

### ISSUE THREAD

**Issue by Aerithlon** [rustdesk/rustdesk-server#284]
Since the upgrade of Rustdesk server to version 1.18, the copy and paste file function on remote computers has been disabled. The clipboard text copy function is still normal, and it is unclear why. At the same time, the Rustdesk client has also been upgraded, and versions 1.20 and 1.21 are not available. Previously, when the server was version 1.17-4 and the client was version 1.19 and 1.20night, the file copy and paste function was available.

自从rustdesk-server升级到1.18版本之后，和远程电脑的复制粘贴文件功能就不能用了，剪切板文本复制功能还是正常的，不清楚是什么原因，同时rustdesk客户端也升级了，1.20和1.21版本都不行，以前server是1.17-4客户端是1.19和1.20night版的时候，文件复制粘贴功能是可用的。

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/2283

**Comment by rustdesk** [comment]
This has nothing to do with server. We had some fix to file copy/paste lately, but the fix obvioulsy made things worse. So we decide to dicard current implementation, we will rewrite it in the near future.
