### ISSUE TITLE
FreeBSD server generates new key on restart

### ISSUE THREAD

**Issue by tschettervictor** [rustdesk/rustdesk-server#288]
**Describe the bug**
When the FreeBSD RustDesk server is restarted it generates a new key, which is not preferable. Version 1.1.8_1

**Describe the environment**
 TrueNAS Core 13 FreeBSD Jail

**How to Reproduce the bug**
Install Using 
pkg install rustdesk-server
Then on each restart the key file contains a different key.

**Expected behavior**
I expect the key to persist across a reboot.

**Comment by madpilot78** [comment]
Hi,

I created and maintain the FreeBSD port.

I have recently observed this too. I have no idea why right now.

This requires investigation. I'll followup here once I have some findings to share.

**Comment by madpilot78** [comment]
ON thing I can confirm right away is that the key is  not regenerated at every restart. It happens "sometimes", caused by unknown factors. This makes debugging the issue more difficult.

**Comment by rustdesk** [comment]
Take time
