### ISSUE TITLE
[Task]: Make clear migration from Docker community version to Pro version

### ISSUE THREAD

**Issue by Dmitry9292** [rustdesk/rustdesk-server#290]
### Are you our team member?

- [X] Yes, I am?

### SubTasks

Firstly - it is not fair what you have done to old versions of rustdesk. In our environment we have set up a bunch of laptops to use this product for a year and now our support cannot connect to the endpoints. 
Now your team wants some money, but instead of making it seamless with migration from community to pro, you just share some script that you should read carefully what it does, spend some time, do extra work - just because your team decided what I should get extra work.
Secondary - How do you manage existing devices with provided encryption keys in case of migration from docker-community version to Pro version that know nothing about Docker containers? There is anything related this case in the documentation?
Please provide clear instructions on how to preserve existing data with the same encryption keys to avoid extra work for your customer's IT team.

P.s. And I am not talking about your version control policy, which is absolutely absurd. You change old releases at will. There are old tags on the Docker Hub that were updated a few days ago. Why is that? Why not make a new release instead of constantly changing your binaries? Some engineers rely on a particular version, and you do a bad job of making version control unclear for them.
Then they go to github to check the source code and then see a code from 1 year ago while the latest version is different from the one on docker hub and updated 3 days ago.
And you charge for the money while you cannot arrange this simple product lifecycle and policy.

Thanks

**Comment by Dmitry9292** [comment]
We had to use version 1.1.9, which was released a year ago. Why did you update to 1.1.8 a week ago?
There was only 1 version available when we decided to use your product which was released by rustdesk team, there was available functionality like web ui and change id. And now you block all "old release" functionality, change the old release to make sure no one will use your previous version.
There is no respect for the community in this policy. Why can I not expect you to change this policy again, even if I buy a license? For example, I will buy a license and you will decide to change the features again a month/year later? I think so because you have already done so.

**Comment by rustdesk** [comment]
First, we do not have 1.1.9 rustdesk server. The one you used is 1.1.4. The closed source version, it did has web portal and change id etc. I stopped selling it about two years ago, because I got some small investment and decided to focus on RustDesk client open source, no time to maintain it. But there are users keep ask me for about how to buy it. So I give them "demo" account for trial for free. Later, I open source RustDesk server without some features (web portable, etc), if you search on this repo, you can see some issues talking about this.

**Comment by rustdesk** [comment]
> docker hub

I guess you are saying https://hub.docker.com/r/rustdesk/rustdesk-server-pro, This old pro version (close source) might have 1.1.9 version for some mistake, I can not remember. But I have never talked about this docker version any where. It is my fault releasing this docker version without any document and not maintaining version control well.

**Comment by rustdesk** [comment]
I can understand your mood, you have used the old Pro version for free for more than 1 years, but now you can not use it. So you are angry.
