### ISSUE TITLE
Is the Rustdesk API Server open source as well?

### ISSUE THREAD

**Issue by windhamwong** [rustdesk/rustdesk-server#30]
I see progress of making the server open source, however, the API server is still closed source and no way to self host it. I wonder is that on the plan or there will be no chance of being open source?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/509

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/issues/26
