### ISSUE TITLE
RustDesk down

### ISSUE THREAD

**Issue by michele-tn** [rustdesk/rustdesk-server#311]
> RustDesk Pro server 1.1.10
> 
> Happens about 50% of the time, I get this this message when trying to connect Win10 to Win10 or MacOS to Win10. Didn't happen before I upgraded to RustDesk Pro. Both computers have gigabit internet connections. 
> 
> ![image](https://github.com/rustdesk/rustdesk/assets/13736705/acb548f5-3fc7-4b6c-9b4d-8b44d93a77a3)

_Originally posted by @mitchellarganbright in https://github.com/rustdesk/rustdesk/discussions/5817_

Hi there,

I've been getting the same error for a couple of hours now. I'm using the free Rustdesk servers.

Thank you very much in advance for your feedback.

Greetings,

Michele

**Comment by michele-tn** [comment]
> have you put in your settings for your server?

Hi dinger1986, first of all thank you very much for the feedback.

I don't use a self-hosted server BUT public servers:

Germany — Hetzner
Ukraine (Kyiv) — dc.volia

Thank you very much in advance for your feedback.

Greetings,

Michele

**Comment by dinger1986** [comment]
but you mention RustDesk Server Pro 1.1.0?

**Comment by michele-tn** [comment]
> but you mention RustDesk Server Pro 1.1.0?



Exactly, as the error is the same one that the user encountered on the PRO version

Thanks in advance


Greetings,

Michele


![image](https://github.com/rustdesk/rustdesk-server/assets/4661972/6f3ebeea-ad07-4e4b-9d24-ff471b332044)

**Comment by michele-tn** [comment]
It seems that now the situation has been restored, I managed to connect.


Thanks so much for the feedback.


Greetings,

Michele

**Comment by rustdesk** [comment]
I guess it is because the public server overloaded. I have no plan to upgrade it yet.

**Comment by michele-tn** [comment]
Thank you very much for the feedback.
