### ISSUE TITLE
我建立服务器成功了，如何连接服务器呢？

### ISSUE THREAD

**Issue by fhmohen** [rustdesk/rustdesk-server#34]
https://rustdesk.com/docs/en/self-host/windows/
我按照上面的创建成功了，我怎么连接服务器呢？

将文件名改成rustdesk-host=ip,key=key.exe 并不能成功！

IP服务器填写上IP，Key填写id_ed25519.pub文件中的Key也不能成功，求解！

**Comment by fhmohen** [comment]
我用提Windows 创建的，感谢！

**Comment by icyflash** [comment]
如何操作的呢

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/763

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/763
