### ISSUE TITLE
Preconfiguring in Filename issue (Windows)

### ISSUE THREAD

**Issue by kombasltd** [rustdesk/rustdesk-server#37]
Hi,

as stated in the documentation, you can set the host and public key in the filename of the client for Windows.

[https://rustdesk.com/docs/en/self-host/install/#key](https://rustdesk.com/docs/en/self-host/install/#key)

I installed the docker version and the content of id_ed25519.pub looks like that:

`uoZ/IMgUtiRqELp/dAyRbP1k9lkCjY4BaM9xUseDdRU=`

When I use host and pub key in the filename of the client, I get something like that which is not a valid Windows filename:

`rustdesk-host=my.remote.host,key=uoZ/IMgUtiRqELp/dAyRbP1k9lkCjY4BaM9xUseDdRU=.exe`

because of the "/".

Any advice or am I missing something?

**Comment by rustdesk** [comment]
Remove id_ed25519 file to generate a new key.

**Comment by kombasltd** [comment]
Works, thanks. maybe add a hint to the documentation for that.
