### ISSUE TITLE
Add binaries compiled with MUSL

### ISSUE THREAD

**Issue by alealexpro100** [rustdesk/rustdesk-server#39]
It would be great not to compile binaries for distributions such as Alpine Linux or Void Linux.
[Here](https://gist.github.com/alealexpro100/9e3f9a00dd1baaf605d64f373a3ab187) is simple shell script to build it under Alpine Linux and (additionally) simple service for running it.

**Comment by rustdesk** [comment]
Thanks, though i do not know Alpine Linux and Void Linux before. :)

**Comment by paspo** [comment]
Statically linked packages (musl) are on the way: https://github.com/rustdesk/rustdesk-server/pull/43

If you're in a hurry, you can download'em from [here](https://github.com/paspo/rustdesk-server/releases/tag/0.0.1), but it's best to wait for the official ones.

**Comment by paspo** [comment]
official ones are reay https://github.com/rustdesk/rustdesk-server/releases/tag/1.1.5-1
