### ISSUE TITLE
Wrong archive in releases

### ISSUE THREAD

**Issue by alealexpro100** [rustdesk/rustdesk-server#44]
Archive of source code on release page (also can be downloaded by [this](https://github.com/rustdesk/rustdesk-server/archive/1.1.5.tar.gz) link) does not contain actual source code of this project.

**Comment by mini-bomba** [comment]
Seems like the reason for this is a [misplaced release tag](https://github.com/rustdesk/rustdesk-server/tree/1.1.5). It is placed in a quite weird place, Github says it's not even in a commit existing in the repo (deleted branch perhaps?)
The release tag should be placed on the actual commit that the binaries were built from, which would usually be wherever the master branch is at.

**Comment by paspo** [comment]
[latest release](https://github.com/rustdesk/rustdesk-server/releases/tag/1.1.5-1), even if flagged as pre-release, contains the correct source code.

All the next releases should do the same as the build process is now automated.
