### ISSUE TITLE
docker run get the error message ( Registered email required (-m option).)

### ISSUE THREAD

**Issue by sfzy** [rustdesk/rustdesk-server#45]
Z ERROR hbbs::lic] Registered email required (-m option). Please pay and register on https://rustdesk.com/server.

**Comment by rustdesk** [comment]
Use the latest version please.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/releases/tag/1.1.5

**Comment by rustdesk** [comment]
![屏幕快照 2022-06-22 下午11 43 35](https://user-images.githubusercontent.com/71636191/175074657-2f4354e4-fbc3-485c-8ede-f0e04782854c.png)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/542#discussioncomment-2772148

**Comment by sfzy** [comment]
Thanks
I searched docker hub, find a image can get work
docker run --name hbbr -p 21117:21117 -p 21119:21119 -v `pwd`:/root -it --net=host thtom/rustdesk-server hbbr
docker run --name hbbs -p 21115:21115 -p 21116:21116 -p 21116:21116/udp -p 21118:21118 -v `pwd`:/root -it --net=host thtom/rustdesk-server hbbs

**Comment by dforel** [comment]
我也遇到了这个问题，后来手动将latest 改为 rustdesk-server:1.1.10-3 就可以了，
我恐怕这是因为我们用了阿里云镜像加速造成的，在这里回复是给下一个可能遇到的人一些提示。

**Comment by qumogu** [comment]
> 我也遇到了这个问题，后来手动将latest 改为 rustdesk-server:1.1.10-3 就可以了， 我恐怕这是因为我们用了阿里云镜像加速造成的，在这里回复是给下一个可能遇到的人一些提示。

非常赞同。我搭建了两次，有阿里云的加速的报错，而没有正常

**Comment by kanseaveg** [comment]
> 我也遇到了这个问题，后来手动将latest 改为 rustdesk-server:1.1.10-3 就可以了， 我恐怕这是因为我们用了阿里云镜像加速造成的，在这里回复是给下一个可能遇到的人一些提示。

感谢大佬提醒，我也碰到了这个问题

```
sudo docker pull rustdesk/rustdesk-server:1.1.10-3
sudo docker run --name hbbs -p 21115:21115 -p 21116:21116 -p 21116:21116/udp -p 21118:21118 -v ./data:/root -td --net=host rustdesk/rustdesk-server:1.1.10-3 hbbs  
sudo docker run --name hbbr -p 21117:21117 -p 21119:21119 -v ./data:/root -td --net=host rustdesk/rustdesk-server:1.1.10-3 hbbr
```


另外，阿里云的环境有点复杂，在这里提醒一下如何设置docker代理：
```
sudo mkdir -p /etc/systemd/system/docker.service.d
sudo vim /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://127.0.0.1:10809"
Environment="HTTPS_PROXY=http://127.0.0.1:10809"

sudo systemctl daemon-reload
sudo systemctl restart docker
```
