### ISSUE TITLE
Reverse Proxy use?

### ISSUE THREAD

**Issue by presence06** [rustdesk/rustdesk-server#46]
Wondering if at this stage it would be wise to run this behind a reverse proxy? Seeing as the login isn't available (from my understanding?) for self hosted yet..

Also, any idea what the proxy settings would need to pass everything through?

**Comment by paspo** [comment]
At this point, it makes no sense. At least with this set of features.

Looks like we're missing an API and a web interface and both could benefit from a reverse proxy.

If these features get restored we can use a reverse proxy to manage SSL termination and so on.

**Comment by pizzaandcheese** [comment]
as @paspo said, there's no current need for reverse proxying with its current feature set ( I cant wait for the API and Web Interface to be available for Self-Hosting!).

That being said, there are some edge cases where it is applicable. For Instance, I currently have rustdesk setup behind [NPM](https://nginxproxymanager.com/) utilizing the port streams. I do this as I don't want to open the server that rustdesk is running on directly to the internet, instead it goes through the one server I do have open to the internet.
