### ISSUE TITLE
请问一下非局域网使用自建服务器问题？

### ISSUE THREAD

**Issue by nczyw** [rustdesk/rustdesk-server#47]
我用docker自建了服务器，在同一局域网下，连接没有问题，当控制端和被控端，不在同一局域网下时，就会一直报错，连接错误，连接被对方关闭？请问这是自建服务器限制呢，还是什么问题呢？谢谢

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/763
