### ISSUE TITLE
Stuck on connecting to the RustDesk network...

### ISSUE THREAD

**Issue by elico** [rustdesk/rustdesk-server#48]
I have changed the ID and RELAY server to my hosted one and when I am restarting the the windows client it states:

Stuck on connecting to the RustDesk network...

Should it be like that?

**Comment by paspo** [comment]
Obviously no.

You should check that:

- the DNS name if your rustdesk-server installation returns an IPv4 address
- the IPv4 address actually matches your server
- the IPv4 is reachable by the client
- the required ports are open (if there are any firewall involved in the path)
- the hbbr/hbbs binaries are running on the server (or the container is running if you're using a container)

**Comment by elico** [comment]
@paspo Thanks.
The issue was a firewall rule.
From one location I had allow all while the other didn't had the allow rule so now after adding the appropriate firewall rules it works great.

Thanks!!

**Comment by yanickrochon** [comment]
@elico what are the "appropriate firewall rules"? I have the same problem and I have tried looking all over the place, I don't get what I'm doing wrong!!
