### ISSUE TITLE
how to customize 'key' (the content of 'id_ed25519.pub')?

### ISSUE THREAD

**Issue by hhhhhliu** [rustdesk/rustdesk-server#56]
how to customize 'key' (the content of 'id_ed25519.pub') in the Linux/docker version?

**Comment by paspo** [comment]
You shouldn't.
This is the public key, which is associated to a private key, contained in a file named `id_ed25519`, placed in the same directory.

If you alter the either part of the key, they won't work anymore.

The key is automatically generated, if the file doesn't exist. You should use the docker volume feature to obtain persistence between container restart/recreation.

**Comment by paspo** [comment]
With recent modifications, you can generate a new kaypair with this command:

```bash
docker run --rm --entrypoint /usr/bin/rustdesk-utils  rustdesk/rustdesk-server-s6:latest genkeypair
```

The output will be something like this:

```bash
Public Key:  8BLLhtzUBU/XKAH4mep3p+IX4DSApe7qbAwNH9nv4yA=
Secret Key:  egAVd44u33ZEUIDTtksGcHeVeAwywarEdHmf99KM5ajwEsuG3NQFT9coAfiZ6nen4hfgNICl7upsDA0f2e/jIA==
```

**Comment by paspo** [comment]
> how to customize 'key' (the content of 'id_ed25519.pub') in the Linux/docker version?

can you explain more in detail your issue?

or close the issue if not needed anymore?

**Comment by somethingstarted** [comment]
the reason why one would want to do this is if we reboot the host computer, occasionally rustdesk will generate a new key. the only problem then is if i have a bunch of computer i now have to walk to them one by one and update the new pub key in the network settings. so it's much better to just not generate new keys, and to let me pick keys once they've been generated once 

this is with the understanding that one would need to back up both the private and public keys once generated of course.
