### ISSUE TITLE
armv7l

### ISSUE THREAD

**Issue by MyLive** [rustdesk/rustdesk-server#6]
Hello @ all,

could you please be so kind and support binarys for the "armv7l" Plattform.

Best regards,
René

**Comment by rustdesk** [comment]
You run the server on arm?

**Comment by MyLive** [comment]
yes, i would like ....
I have a RasPi :-) i would like to run the Server an the Pi ...

**Comment by rustdesk** [comment]
But I can not find a Pi to build it.

**Comment by MyLive** [comment]
Ich kann es auf einem RPI Bauen :-) falls gewünscht

**Comment by initdc** [comment]
Try github action or `docker buildx`

**Comment by RobotsAreCrazy** [comment]
Can you do a arm64 aarch server build not many remote access options on rpi tbh

**Comment by RobotsAreCrazy** [comment]
> But I can not find a Pi to build it.

I would build it if only i knew what was needed

**Comment by rustdesk** [comment]
It is free and open source now. https://rustdesk.com/docs/en/self-host/
