### ISSUE TITLE
1.1.6版本，CPU利用率过高

### ISSUE THREAD

**Issue by funny-fury** [rustdesk/rustdesk-server#63]
<details><summary>1.1.5</summary>

![1.1.15](https://i.imgur.com/hHebYA4.png)

</details>

<details><summary>1.1.6</summary>

![1.1.6](https://i.imgur.com/VwZ1hbR.png)

![1.1.6](https://i.imgur.com/m4e6Img.png)

</details>

clone目前的最新代码下来构建同样的现象  
希望可以解决 谢谢

**Comment by rustdesk** [comment]
But my 1.1.6 on Windows is as low as 1.1.5.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/issues/186

**Comment by rustdesk** [comment]
Can you try out this?

![image](https://user-images.githubusercontent.com/71636191/220841534-9bd479d8-1bf5-4dca-8e6e-cc0c69a308ce.png)
