### ISSUE TITLE
improve docs

### ISSUE THREAD

**Issue by MisterMountain** [rustdesk/rustdesk-server#71]
docs should be divided into a docker part and a part without using docker

**Comment by paspo** [comment]
In my opinion, we should use the [wiki](https://github.com/rustdesk/rustdesk-server/wiki).

There's no way we can fit everything in the readme

**Comment by MisterMountain** [comment]
Actually i made that issue in the wrong repo

**Comment by MisterMountain** [comment]
Actually i made that issue in the wrong repo
