### ISSUE TITLE
更改id时显示服务器关闭了此功能-自建服务器

### ISSUE THREAD

**Issue by mx-mixed** [rustdesk/rustdesk-server#74]
更改id时显示服务器关闭了此功能-自建服务器,
想问下更改id的功能需要在启动时加什么参数吗

**Comment by wxlg1117** [comment]
因为目前自建中继续服务器版本不支持该功能吧

**Comment by mx-mixed** [comment]
使用的是最新版的服务器，刚刚看到之前有人提这个问题，应该是移除这个功能了

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server/issues/22

**Comment by foxppt** [comment]
github提issue是不是该讲讲武德 :D , 用英文啊，方便外国友人。

**Comment by Bell-see** [comment]
> github提issue是不是该讲讲武德 :D , 用英文啊，方便外国友人。

都一样 谷歌翻译么 都能看得懂就是了😂
