### ISSUE TITLE
With a key rustdesk only in the same network, different network doesnt work

### ISSUE THREAD

**Issue by Andre-Lehrmann** [rustdesk/rustdesk-server#79]
**Describe the bug you encountered:**
if rustdesk is configured with a security key (Option -k _) , then a remote connection will only work on the same subnet. A client in another network cannot be reached. But it is possible without a key.

**What did you expect to happen instead?**
That rustdesk can connect to a client in another subnet

**How did you install `RustDesk`?**
Create a yml, based on the rustdesk installation manuel with Parameter -k _
docker-compose up -d 

**RustDesk version and environment**
Server - latest Docker Image from 27.7.2022 from github
Client 1 - Android 1.1.10.-1
Client 2 + 3 - Windows rustdesk 1.1.9

![Rustdeskkeyproblem](https://user-images.githubusercontent.com/110154835/181438871-d2248c1a-50e3-4226-b6cb-e52e595e194b.jpg)

Nice greetings
André Lehrmann

**Comment by paspo** [comment]
@Andre-Lehrmann can you paste here your `docker-compose.yaml` and the containers logs?

**Comment by Andre-Lehrmann** [comment]
> Probably you should copy the keyfiles from hbbs to hbbr folder. That resolved the issue for me.
I make the copy.
That doesnt solved my problem.

**Comment by Andre-Lehrmann** [comment]
> @Andre-Lehrmann can you paste here your `docker-compose.yaml` and the containers logs?

Here ist the docker-compose.yml File, later post i the container logs.


version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r andre-lehrmann.de:21117 -k _
    volumes:
      - ./hbbs:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - ./hbbr:/root
    networks:
      - rustdesk-net
    restart: unless-stopped

**Comment by paspo** [comment]
next time, please use the *code* tag when you paste files or logs, for improved readability.
Especially for logs.

**Comment by Andre-Lehrmann** [comment]
These are the docker logs.
I have changed key and IPs.


[7167c2c19e0ffb96379df99022ad9b112e7734ec189752a05cc9cd003274af73-json.log](https://github.com/rustdesk/rustdesk-server/files/9207517/7167c2c19e0ffb96379df99022ad9b112e7734ec189752a05cc9cd003274af73-json.log)

````Shell
{"log":"[2022-07-27 14:51:10.086794 +00:00] INFO [src/common.rs:111] Private key comes from id_ed25519\n","stream":"stdout","time":"2022-07-27T14:51:10.087185875Z"}
{"log":"[2022-07-27 14:51:10.086841 +00:00] INFO [src/relay_server.rs:574] Key: Highsecuritykeynumber\n","stream":"stdout","time":"2022-07-27T14:51:10.087235438Z"}
{"log":"[2022-07-27 14:51:10.086862 +00:00] INFO [src/relay_server.rs:60] #blacklist(blacklist.txt): 0\n","stream":"stdout","time":"2022-07-27T14:51:10.087240875Z"}
{"log":"[2022-07-27 14:51:10.086875 +00:00] INFO [src/relay_server.rs:75] #blocklist(blocklist.txt): 0\n","stream":"stdout","time":"2022-07-27T14:51:10.087244455Z"}
{"log":"[2022-07-27 14:51:10.086877 +00:00] INFO [src/relay_server.rs:81] Listening on tcp 0.0.0.0:21117\n","stream":"stdout","time":"2022-07-27T14:51:10.087247973Z"}
{"log":"[2022-07-27 14:51:10.086883 +00:00] INFO [src/relay_server.rs:83] Listening on websocket 0.0.0.0:21119\n","stream":"stdout","time":"2022-07-27T14:51:10.087251416Z"}
{"log":"[2022-07-27 14:51:10.086886 +00:00] INFO [src/relay_server.rs:85] Start\n","stream":"stdout","time":"2022-07-27T14:51:10.087254911Z"}
{"log":"[2022-07-27 14:51:10.086983 +00:00] INFO [src/relay_server.rs:104] DOWNGRADE_THRESHOLD: 0.66\n","stream":"stdout","time":"2022-07-27T14:51:10.087333594Z"}
{"log":"[2022-07-27 14:51:10.087013 +00:00] INFO [src/relay_server.rs:113] DOWNGRADE_START_CHECK: 1800s\n","stream":"stdout","time":"2022-07-27T14:51:10.087346547Z"}
{"log":"[2022-07-27 14:51:10.087016 +00:00] INFO [src/relay_server.rs:122] LIMIT_SPEED: 4Mb/s\n","stream":"stdout","time":"2022-07-27T14:51:10.087352786Z"}
{"log":"[2022-07-27 14:51:10.087018 +00:00] INFO [src/relay_server.rs:132] TOTAL_BANDWIDTH: 1024Mb/s\n","stream":"stdout","time":"2022-07-27T14:51:10.087374045Z"}
{"log":"[2022-07-27 14:51:10.087028 +00:00] INFO [src/relay_server.rs:146] SINGLE_BANDWIDTH: 16Mb/s\n","stream":"stdout","time":"2022-07-27T14:51:10.087378456Z"}
{"log":"[2022-07-28 08:36:04.089142 +00:00] INFO [src/relay_server.rs:446] New relay request c3807ab5-7600-415b-825c-e0ea3a9535f3 from 8.8.8.8:23705\n","stream":"stdout","time":"2022-07-28T08:36:04.089799949Z"}
{"log":"[2022-07-28 08:36:23.378364 +00:00] INFO [src/relay_server.rs:446] New relay request 8033f0c0-3f7b-422a-b947-d43f0e45bb9e from 8.8.8.8:25041\n","stream":"stdout","time":"2022-07-28T08:36:23.378649231Z"}
{"log":"[2022-07-28 08:36:43.767052 +00:00] INFO [src/relay_server.rs:446] New relay request 626ac47a-3d4a-5cca-92a9-87bb8809d0c0 from 8.8.8.8:26384\n","stream":"stdout","time":"2022-07-28T08:36:43.767336051Z"}
{"log":"[2022-07-28 08:37:06.032146 +00:00] INFO [src/relay_server.rs:446] New relay request d3d70926-a762-46a7-8f93-86418f85c748 from 8.8.8.8:6238\n","stream":"stdout","time":"2022-07-28T08:37:06.032722556Z"}

````


[fd2eefbdc7b565b7b3cb9cb8d76ce3fef9b122cff059f0f67a682d8677832445-json.log](https://github.com/rustdesk/rustdesk-server/files/9207518/fd2eefbdc7b565b7b3cb9cb8d76ce3fef9b122cff059f0f67a682d8677832445-json.log)

````Shell
{"log":"[2022-07-27 14:51:21.398298 +00:00] INFO [src/common.rs:111] Private key comes from id_ed25519\n","stream":"stdout","time":"2022-07-27T14:51:21.398520572Z"}
{"log":"[2022-07-27 14:51:21.398827 +00:00] INFO [src/rendezvous_server.rs:1159] Key: Highsecuritykeynumber\n","stream":"stdout","time":"2022-07-27T14:51:21.400338621Z"}
{"log":"[2022-07-27 14:51:21.398860 +00:00] INFO [src/peer.rs:82] DB_URL=./db_v2.sqlite3\n","stream":"stdout","time":"2022-07-27T14:51:21.400357293Z"}
{"log":"[2022-07-27 14:51:21.402389 +00:00] INFO [src/rendezvous_server.rs:103] serial=0\n","stream":"stdout","time":"2022-07-27T14:51:21.402508021Z"}
{"log":"[2022-07-27 14:51:21.402416 +00:00] INFO [src/common.rs:41] rendezvous-servers=[]\n","stream":"stdout","time":"2022-07-27T14:51:21.402560744Z"}
{"log":"[2022-07-27 14:51:21.402421 +00:00] INFO [src/rendezvous_server.rs:105] Listening on tcp/udp 0.0.0.0:21116\n","stream":"stdout","time":"2022-07-27T14:51:21.402565094Z"}
{"log":"[2022-07-27 14:51:21.402423 +00:00] INFO [src/rendezvous_server.rs:106] Listening on tcp 0.0.0.0:21115, extra port for NAT test\n","stream":"stdout","time":"2022-07-27T14:51:21.402568607Z"}
{"log":"[2022-07-27 14:51:21.402425 +00:00] INFO [src/rendezvous_server.rs:107] Listening on websocket 0.0.0.0:21118\n","stream":"stdout","time":"2022-07-27T14:51:21.402572705Z"}
{"log":"[2022-07-27 14:51:21.402468 +00:00] INFO [libs/hbb_common/src/udp.rs:35] Receive buf size of udp 0.0.0.0:21116: Ok(212992)\n","stream":"stdout","time":"2022-07-27T14:51:21.403398713Z"}
{"log":"[2022-07-27 14:51:21.402648 +00:00] INFO [src/rendezvous_server.rs:136] mask: None\n","stream":"stdout","time":"2022-07-27T14:51:21.403412546Z"}
{"log":"[2022-07-27 14:51:21.402651 +00:00] INFO [src/rendezvous_server.rs:137] local-ip: \"172.18.0.3\"\n","stream":"stdout","time":"2022-07-27T14:51:21.403416697Z"}
{"log":"[2022-07-27 14:51:21.404596 +00:00] INFO [src/common.rs:41] relay-servers=[\"andre-lehrmann.de:21117\"]\n","stream":"stdout","time":"2022-07-27T14:51:21.404719752Z"}
{"log":"[2022-07-27 14:51:21.404767 +00:00] INFO [src/rendezvous_server.rs:154] ALWAYS_USE_RELAY=N\n","stream":"stdout","time":"2022-07-27T14:51:21.404885657Z"}
{"log":"[2022-07-27 14:51:21.404793 +00:00] INFO [src/rendezvous_server.rs:174] Start\n","stream":"stdout","time":"2022-07-27T14:51:21.404898544Z"}
{"log":"[2022-07-28 08:32:03.563822 +00:00] INFO [src/peer.rs:100] update_pk 446289392 7.7.7.7:1448 [52, 52, 57, 98, 51, 52, 52, 51, 45, 57, 100, 57, 52, 45, 52, 102, 54, 50, 45, 98, 54, 51, 97, 45, 53, 57, 49, 97, 56, 101, 48, 98, 102, 101, 101, 100] [159, 62, 209, 8, 84, 28, 202, 35, 36, 140, 204, 217, 80, 48, 41, 89, 60, 72, 250, 222, 130, 216, 129, 208, 210, 61, 155, 134, 26, 247, 14, 230]\n","stream":"stdout","time":"2022-07-28T08:32:03.564983398Z"}
{"log":"[2022-07-28 08:33:27.605660 +00:00] INFO [src/rendezvous_server.rs:578] IP change of 1304131872 from 9.9.9.9:47972 to 8.8.8.8:7110\n","stream":"stdout","time":"2022-07-28T08:33:27.606651979Z"}
{"log":"[2022-07-28 08:33:27.949566 +00:00] INFO [src/peer.rs:100] update_pk 1304131872 8.8.8.8:7110 [251, 103, 217, 15, 198, 233, 75, 70, 70, 41, 202, 174, 155, 86, 147, 24, 11, 245, 17, 244, 194, 223, 227, 236, 59, 137, 148, 69, 123, 111, 245, 169] [251, 103, 217, 15, 198, 233, 75, 70, 70, 41, 202, 174, 155, 86, 147, 24, 11, 245, 17, 244, 194, 223, 227, 236, 59, 137, 148, 69, 123, 111, 245, 169]\n","stream":"stdout","time":"2022-07-28T08:33:27.950139731Z"}
{"log":"[2022-07-28 08:33:27.952386 +00:00] INFO [src/peer.rs:128] pk updated instead of insert\n","stream":"stdout","time":"2022-07-28T08:33:27.952617104Z"}
````

**Comment by paspo** [comment]
both hbbr and hbbs are using the private key from `id_ed25519` file, that's good. We suppose they're using the same file, or files with same contents.

8:32:03 - id 446289392 connects to hbbs from ip 7.7.7.7
8:33:27 - id 1304131872 connects to hbbs from ip 8.8.8.8
8:36:04 - ip 8.8.8.8 requests a relayed connection to hbbr
8:36:23 - ip 8.8.8.8 requests a relayed connection to hbbr
8:36:43 - ip 8.8.8.8 requests a relayed connection to hbbr
8:37:06 - ip 8.8.8.8 requests a relayed connection to hbbr

I suppose you're trying to connect from id 1304131872 to id 446289392
I don't know the translation between these IDs and the picture in your issue request.

Can you confirm that you set up the correct public key in all clients? (watch for unexpected spaces and so on)

**Comment by Andre-Lehrmann** [comment]
Btw. thx for your time and help!
The key files are the same.
7.7.7.7 is client 2
8.8.8.8 is client 1
I think the keys in all clients are correct, because, when i put the client 1 in the same client 2 networt, it works.

**Comment by paspo** [comment]
So the android client (client1) has the correct key, otherwise it won't connect when using wifi.

Can you try to disconnect one of the two PCs from the lan and connect via hotspot (via client1)?

**Comment by Andre-Lehrmann** [comment]
> So the android client (client1) has the correct key, otherwise it won't connect when using wifi.
> 
> Can you try to disconnect one of the two PCs from the lan and connect via hotspot (via client1)?

That's what I tried. Client 2 is a laptop and I have brought Client 1 + 2 into a Wlan network. Then it works. If Client 1 or Client 2 or both are directly on the Internet, then it will not work. I think I need to use wireshark. Maybe then I can see the error. I noticed with my firewall that Port 21114 is being addressed. However, this is not included in the firewall rules and is dropped. Does port 21114 also have to be released in the firewall?

**Comment by paspo** [comment]
AFAIK port 21114 is not used. In fact, it's not mentioned in `docker-compose.yaml`.

When "Client 1 or Client 2 or both are directly on the Internet", you mean "on cellular connecion", I think. This type of connection can sometimes be NATTED.

**Comment by paspo** [comment]
port 21114:
https://github.com/rustdesk/rustdesk/discussions/522

**Comment by Andre-Lehrmann** [comment]
Ohh, that is strange. 
![Rustdeskkeyproblem2](https://user-images.githubusercontent.com/110154835/181694816-3f15b384-2f9c-4613-8b25-abdc4ed8f370.jpg)

Rustdesk, with keys, makes a direct Connection to the other client in the same subnet.
Why is the trafiic not routed over the rustdesk server?

I think, that is the main problem.

**Comment by paspo** [comment]
That's normal, and in fact, you want that for performance.
If you want to always use the relay server, you have to set the environment variable `ALWAYS_USE_RELAY` to `Y` for `hbbs`.

**Comment by Andre-Lehrmann** [comment]
OK, i thought every traffic is going over the rustdesk Server, my vault.
With relay Server the connection between client1 and client2, both directly connected in the Internet now works,
In our company net is it not working. I think the firewall rules are very strict.
It is for private use, so i cant get a new firewall rule in my company :-)
But I think, the Port 5938 is open. I give it a try, and change hbbs to 5938.....
Thanks for your time and help, i close now this post.

**Comment by Andre-Lehrmann** [comment]
Thanks for the tool rustdesk.
