### ISSUE TITLE
External access via reverse proxy ?

### ISSUE THREAD

**Issue by Fabeuss** [rustdesk/rustdesk-server#80]
Hi, and thanks for your work, that's amazing !

I have successfully installed the 2 containers (hhbs and hbbr) on my synology nas and it works like a charm at home, but I would like to access my devices from outside...
I tried to replace the local address in thze command field by the reverse proxy url but it doesn't work, is it possible and how please?

Thanks

**Comment by paspo** [comment]
reverse proxy is useful only for http(s) connections, which is not the case for rustdesk-server.
you should expose the ports via port-forwarding on the router

**Comment by Fabeuss** [comment]
Hi paspo, 
I understand, thanks for your reply, will try that : https://mariushosting.com/how-to-install-rustdesk-on-your-synology-nas/

**Comment by paspo** [comment]
that assumes you're using a synology router and will setup port forwarding accordingly.

**Comment by Fabeuss** [comment]
I just configured this on my router (not synology) and everything works, thanks for your help
