### ISSUE TITLE
Missing documentation and questions.

### ISSUE THREAD

**Issue by simeononsecurity** [rustdesk/rustdesk-server#81]
So, following the self-hosting options you end up with two docker containers. One running the hbbs and one the hbbr binaries.
The logs from which output nothing useful other than maybe your public ip if you didn't already know that.
Lets say you're smart enough to get that far in the instructions, you have your dns name and or you know your server's ip address, and you know the pub key that is needed to connect. Well the instructions for the client make no sense whatsoever. 

Under the ID/Relay Server options, you have 4 boxes. Some youtubers and your documentation say to fill in the ID server or the relay server with the information from the newly created self host server. However, on 1.1.9, the only version I've tested, it doesn't work unless I only include the server information under the relay options. This doesn't seem to accomplish much.  As it just shows that I still need to set up my own server.

Available ID/Relay Server options:
![image](https://user-images.githubusercontent.com/4913771/182065859-c2fc373a-6104-48f3-b31c-44548bef039a.png)
When just relay server is specified:
![image](https://user-images.githubusercontent.com/4913771/182066077-2f14dfdb-9017-4322-89c6-04edc1ff8efd.png)
When ID server is specified:
![image](https://user-images.githubusercontent.com/4913771/182066102-d042f58a-a51f-4596-831e-8541f3b3e306.png)
![image](https://user-images.githubusercontent.com/4913771/182066116-f9917a6d-133c-41ec-be59-e9d5535b7c6b.png)

I'm pretty versed in setting up services,  servers, and networking in general. I've tested that the name resolves on all of my clients and that the ports are appropriately open. I followed the official instructions here:
- https://rustdesk.com/docs/en/self-host/install/
- https://rustdesk.com/docs/en/self-host/install/#step-3--set-hbbshbbr-address-on-client-side

Lastly, I've tried following alternative instructions to no avail:
- https://shownotes.opensourceisawesome.com/rustdesk/

Also, in the documentation for your docker run options, you don't have -d specified and you also have --rm specified. This is an incorrect configuration unless its solely for testing. Also, if you have --net=host specified, you don't need to specify any of the -p options.

It needs to be instead for -host options:
```bash
sudo docker image pull rustdesk/rustdesk-server:latest
sudo docker run -td --name hbbs -v `pwd`:/root --net=host rustdesk/rustdesk-server:latest hbbs -r ip/dns:port
sudo docker run -td --name hbbr -v `pwd`:/root --net=host rustdesk/rustdesk-server:latest hbbr 
```
Or for port options it needs to be:
```bash
sudo docker image pull rustdesk/rustdesk-server:latest
sudo docker run -td --name hbbs -p 21115:21115 -p 21116:21116 -p 21116:21116/udp -p 21118:21118 -v `pwd`:/root rustdesk/rustdesk-server:latest hbbs -r ip/dns:port
sudo docker run -td --name hbbr -p 21117:21117 -p 21119:21119 -v `pwd`:/root rustdesk/rustdesk-server:latest hbbr 
```

I apologize if this sounds like a rant. But I really do want this product to succeed.  But if I can't get this product working at my skill level, I can't support it or recommend it for anyone. We need the product to work foremost and we need better documentation.

**Comment by paspo** [comment]
@simeononsecurity don't worry for the rant, you'll make it up by helping us with the [documentation](https://github.com/rustdesk/doc.rustdesk.com) ;)

But first, a little bit of history: RustDesk wasn't always open-source; when the developers changed the license, they decided to not open-source some parts of the product. That's why you se some features in the client that are not implemented on the server side.

To be more specific on the client options:

- ID server: is the location of hbbs (port 21117)
- relay server: is the location of hbbr
- API server: is the location of the (missing) API server (port 21114)

relay server location is usually not needed: when the client connects to hbbs, this is sending back the relay location (hbbs has a dedicated `-r` parameter)

I absolutely understand your position on the "ports" question, I had the same complains some weeks ago.
The fact is that if hbbs is running on host networking, it can obtain all the informations it needs to allow direct peer to peer connecion; otherwise, all the connections must be relayed (through hbbr). There's no way around this (in docker / k8s).

**Comment by simeononsecurity** [comment]
> @simeononsecurity don't worry for the rant, you'll make it up by helping us with the [documentation](https://github.com/rustdesk/doc.rustdesk.com) ;)
> 
> But first, a little bit of history: RustDesk wasn't always open-source; when the developers changed the license, they decided to not open-source some parts of the product. That's why you se some features in the client that are not implemented on the server side.
> 
> To be more specific on the client options:
> 
> * ID server: is the location of hbbs (port 21117)
> * relay server: is the location of hbbr
> * API server: is the location of the (missing) API server (port 21114)
> 
> relay server location is usually not needed: when the client connects to hbbs, this is sending back the relay location (hbbs has a dedicated `-r` parameter)
> 
> I absolutely understand your position on the "ports" question, I had the same complains some weeks ago. The fact is that if hbbs is running on host networking, it can obtain all the informations it needs to allow direct peer to peer connecion; otherwise, all the connections must be relayed (through hbbr). There's no way around this (in docker / k8s).

That being said, nothing is broken by leaving the port mapping there. However I would still change the -it to -td and remove the --rm option.
I've submitted a PR with the changes https://github.com/rustdesk/doc.rustdesk.com/pull/56

After sleeping on it and also tinkering more a bit I had issues using the host network options while using a VPS. 
Not sure what the issue was but, it didn't let me connect until I changed my network type to bridge.  I have other services running under host network fine that don't have any port conflicts so it just seems like the server was refusing the connections while using the host network...  Works now though so I'm fine with the relay.

You'd think however that I'd need to specify the other configuration options now that it's in bridge mode and the relay is required. Might be smart to have those boxes populate when they are autofilled from the ID server rather than leaving them blank.

**Comment by rustdesk** [comment]
@paspo are you ok with this change? https://github.com/rustdesk/doc.rustdesk.com/pull/56/files

**Comment by paspo** [comment]
@rustdesk https://github.com/rustdesk/doc.rustdesk.com/pull/56#pullrequestreview-1058618925
