### ISSUE TITLE
如何实现网络唤醒呢

### ISSUE THREAD

**Issue by dysysqf** [rustdesk/rustdesk-server#87]
如何实现网络唤醒呢

**Comment by paspo** [comment]
Wake-on-lan is not something you can do server-side...

WOL is one pc/server/something sending a particular packet to an ethernet mac address, which means no routing; so the packet must be sent from the same network. This must be implemented client-side.

Next time, please, write in english.

**Comment by nik231180** [comment]
> WOL — это один компьютер/сервер/что-то, отправляющее определенный пакет на MAC-адрес Ethernet, что означает отсутствие маршрутизации; поэтому пакет должен быть отправлен из той же сети. Это должно быть реализовано на стороне клиента.

Wake-on-LAN technology works not only in a local area network. Thanks to this technology, you can turn on your computer, even if you are overseas. In TeamWeaver, that's how it worked.
