### ISSUE TITLE
我执行下面代码后，只需要在客户端填写ip就行了么？

### ISSUE THREAD

**Issue by bbhxwl** [rustdesk/rustdesk-server#92]
执行下面代码后，是只需要写ID服务器和中继服务器，就可以用了么？我目前看是这样，但是这样安全么？我也不知道我设置的成功了没。是走我服务器的么。

docker run  --name hbbs --restart=always  -p 21115:21115 -p 21116:21116 -p 21116:21116/udp -p 21118:21118 -v /var/www/rustdesk/:/root -itd --net=host  rustdesk/rustdesk-server hbbs -r 外网ip

docker run --name hbbr  --restart=always -p 21117:21117 -p 21119:21119 -v /var/www/rustdesk/:/root -itd --net=host  rustdesk/rustdesk-server hbbr

**Comment by zhaoxuan** [comment]
我在运行 hbbs 但是提示我 Please pay and register on https://rustdesk.com/server
