### ISSUE TITLE
Hope hbbr and hbbs support wss

### ISSUE THREAD

**Issue by fcwys** [rustdesk/rustdesk-server#94]
In this way, the web static resources can make better use of the service-worker feature to improve the loading speed.

**Comment by fcwys** [comment]
When the web client is remotely loaded, static resources can be cached using https, but the ws connection is not available in the https environment, so it is necessary to support wss to adapt.

**Comment by rustdesk** [comment]
hbbr/hbbs will not support wss, you should add wss support with nginx etc.

**Comment by fcwys** [comment]
ok

**Comment by TBG-FR** [comment]
> hbbr/hbbs will not support wss, you should add wss support with nginx etc.

Why not ? What's the issue with WSS ? 🤔

**Comment by TBG-FR** [comment]
> When the web client is remotely loaded, static resources can be cached using https, but the ws connection is not available in the https environment, so it is necessary to support wss to adapt.

As per @rustdesk's answer, if you want an HTTPS Web Client, you need to figure out a good Reverse Proxy configuration, to proxy WSS (from Web Client) to WS (Server). If you're interested, see Working Traefik configuration for HTTPS RustDesk Web Client 😉 https://github.com/rustdesk/rustdesk/discussions/6023#discussioncomment-868756
