### ISSUE TITLE
自建服务器运行一段时间后自动退出

### ISSUE THREAD

**Issue by i2Worker** [rustdesk/rustdesk-server#96]
我在阿里云VPS服务器上（操作系统CentOS Linux release 7.9.2009，内核版本Linux 5.19.0-1.el7.elrepo.x86_64），安装了RustDesk自建服务器（版本是1.1.6），运行hbbr、hbbs后，家里电脑和公司电脑都正确安装RuetDesk的客户端（版本均是1.19），在家里电脑通过TCP隧道，远程桌面连接，公司电脑，能够正常连接操作，操作一段时间完成任务退出后，发现自建服务器hbbr、hbbs均自动退出了，重启启动后才可以连接。具体日志见图片。
![RustDesk](https://user-images.githubusercontent.com/11516760/184519879-8d4b9f90-dd44-4602-88ee-0bd843da8e7e.png)

**Comment by wxlg1117** [comment]
memory allocation ...
查看是否内存不足

**Comment by i2Worker** [comment]
后来把Linux的内核降级为5.18.12之后，这个问题没有出现了，可能是因为更新内核到5.19之后出现这个问题的
