### ISSUE TITLE
Samsung Galaxy Tab S7+ (probably others) keyboard cover issues

### ISSUE THREAD

**Issue by undrwater** [rustdesk/rustdesk-server#97]
**Describe the bug**
The magnetically attached keyboard cover sends double characters to the remote machine. Additionally, the track pad mouse does not control the remote mouse. The only way to do this is from touch-drag gestures on the screen.

**Describe the environment**
 Android 12

**How to Reproduce the bug**
Run rustdesk on Samsung Galaxy Tab S7+ and likely others

**Expected behavior**
Keyboard should send single characters, and mouse should control remote mouse.

Let me know if you need logs or for me to perform testing. I'm happy to do it.

**Comment by paspo** [comment]
how this should relate to a server issue?

maybe @rustdesk should transfer this issue to the [client repo](https://github.com/rustdesk/rustdesk-server/issues)

**Comment by rustdesk** [comment]
duplicate， please search in  rustdesk repo issues
