### ISSUE TITLE
Rustserver not working propertly

### ISSUE THREAD

**Issue by SmartByteKam** [rustdesk/rustdesk-server#98]
**Everything was done exactly according to the instructions**

Windows 2019, CentOS 7.9, Ubuntu Server 22.04 (everything on Microsoft Hyper-V server)

Docker image loaded without errors. Docker status shows both hbbs and hbbr are running.  Then I configured the ID/relay server in the client with the debian server IP. The clients just show "Connecting to the RustDesk network" . I tried both the lan IP, public IP, and the dynamic DNS host. I have forwarded TCP/UDP ports 21115-21119

On a Windows machine, I am able to connect from the rustdesk clients only using the LAN IP. I have disabled the built-in Windows firewall. I am able to connect to the Windows machine from outside the LAN using DNS-name.

Tried the s6 images, both the latest and latest-amd64 It didn't work. 
Tried docker and docker-compose (v1*, v2*) - and nothing

Tried start rustserver without docker - same problem. 
Tried RUST_LOG=debug ./hbbs - nothing useful in logs

**Comment by raystek** [comment]
I have similar experience. I could only get Rustdek server working in Debian running on a physical machine. No luck on hyper-v VMs. I have other Debian VMs running correctly on hyperv.

On the physical machine,  only LAN clients can connect using the server's LAN IP. I am able to get a "Ready" status for clients outside the LAN using the DNS name but they could not connect to any machines.

**Comment by raystek** [comment]
Not sure what happened. I hadn't changed any config. Tonight I tried the server again and everything worked!
I use pm2 to start RD on the physical machine. I use a different set of ports (33300 - 33304), instead of the default 21116 - 21119.
My commands to start the server:
pm2 ./hbbs -- -p 33301 -r remote.mydomain.com:33302
pm2 ./hbbr -p 33302

On the clients, I use remote.mydomain.com:33301 for ID Server, and remote.mydomain.com:33302 for Relay Server

**Comment by julianmaria** [comment]
The same here on Hyper-V  Centos 7 & Rocky Linux running server (hbbs / hbbr) disabling firewall, changing ports, etc. No client connections

**Comment by SmartByteKam** [comment]
I realized that the developers do not cope with the flow of problems of their product. It's a pity. Let's see what happens in a year or two
